(function (lib, img, cjs) {

var p; // shortcut to reference prototypes

// stage content:
(lib.screen_151x265 = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{loop:1});

	// timeline functions:
	this.frame_1 = function() {
		var _this = this;
		function delay(time) { setTimeout(gotoNextFrame, time * 1000); }
		function gotoNextFrame() { _this.play(); }
		_this.stop();
		delay(3.3);
	}
	this.frame_2 = function() {
		var _this = this;
		function delay(time) { setTimeout(gotoNextFrame, time * 1000); }
		function gotoNextFrame() { _this.play(); }
		_this.stop();
		delay(2);
		
		_this.MC_Banner.gotoAndPlay("part1");
	}
	this.frame_3 = function() {
		var _this = this;
		function delay(time) { setTimeout(gotoNextFrame, time * 1000); }
		function gotoNextFrame() { _this.play(); }
		_this.stop();
		delay(2);
		
		_this.MC_Banner.gotoAndPlay("part2");
	}
	this.frame_4 = function() {
		var _this = this;
		function delay(time) { setTimeout(gotoNextFrame, time * 1000); }
		function gotoNextFrame() { _this.play(); }
		_this.stop();
		delay(2);
		
		_this.MC_Banner.gotoAndPlay("part3");
	}
	this.frame_5 = function() {
		var _this = this;
		function delay(time) { setTimeout(gotoNextFrame, time * 1000); }
		function gotoNextFrame() { _this.play(); }
		_this.stop();
		delay(2);
		
		_this.MC_Banner.gotoAndPlay("part4");
	}
	this.frame_6 = function() {
		var _this = this;
		function delay(time) { setTimeout(gotoNextFrame, time * 1000); }
		function gotoNextFrame() { _this.play(); }
		_this.stop();
		delay(2);
		
		_this.MC_Banner.gotoAndPlay("part5");
	}
	this.frame_7 = function() {
		var _this = this;
		function delay(time) { setTimeout(gotoNextFrame, time * 1000); }
		function gotoNextFrame() { _this.play(); }
		_this.stop();
		delay(2);
		
		_this.MC_Banner.gotoAndPlay("part6");
	}
	this.frame_8 = function() {
		var _this = this;
		function delay(time) { setTimeout(gotoNextFrame, time * 1000); }
		function gotoNextFrame() { _this.play(); }
		_this.stop();
		delay(2);
		
		_this.MC_Banner.gotoAndPlay("part7");
	}
	this.frame_9 = function() {
		var _this = this;
		function delay(time) { setTimeout(gotoNextFrame, time * 1000); }
		function gotoNextFrame() { _this.play(); }
		_this.stop();
		delay(2);
		
		_this.MC_Banner.gotoAndPlay("part8");
	}
	this.frame_10 = function() {
		var _this = this;
		function delay(time) { setTimeout(gotoNextFrame, time * 1000); }
		function gotoNextFrame() { _this.play(); }
		_this.stop();
		delay(2);
		
		_this.MC_Banner.gotoAndPlay("part9");
	}
	this.frame_11 = function() {
		stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(1).call(this.frame_1).wait(1).call(this.frame_2).wait(1).call(this.frame_3).wait(1).call(this.frame_4).wait(1).call(this.frame_5).wait(1).call(this.frame_6).wait(1).call(this.frame_7).wait(1).call(this.frame_8).wait(1).call(this.frame_9).wait(1).call(this.frame_10).wait(1).call(this.frame_11));

	// MC_Banner
	this.MC_Banner = new lib.MC_Banner();
	this.MC_Banner.setTransform(75.5,132.5,1,1,0,0,0,75.5,132.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.MC_Banner}]}).wait(12));

	// simple bg
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AryUsMAAAgpYIXlAAMAAAApYg");
	this.shape.setTransform(0.1,0.1,1,1,0,0,0,-75.4,-132.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).wait(12));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,151,265);


// symbols:
(lib.member_1 = function() {
	this.initialize(img.member_1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,27,36);


(lib.member_2 = function() {
	this.initialize(img.member_2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,28,36);


(lib.member_3 = function() {
	this.initialize(img.member_3);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,27,36);


(lib.member_4 = function() {
	this.initialize(img.member_4);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,28,36);


(lib.member_5 = function() {
	this.initialize(img.member_5);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,27,36);


(lib.member_big_1 = function() {
	this.initialize(img.member_big_1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,32,32);


(lib.member_big_2 = function() {
	this.initialize(img.member_big_2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,32,32);


(lib.member_big_3 = function() {
	this.initialize(img.member_big_3);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,32,32);


(lib.reel = function() {
	this.initialize(img.reel);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,151,698);


(lib.touch_mc = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(2,1,1).p("AAAhjQApAAAdAdQAeAeAAAoQAAApgeAdQgdAegpAAQgoAAgegeQgdgdAAgpQAAgoAdgeQAegdAoAAg");
	this.shape.setTransform(10,10);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,20,20);


(lib.statusBarWhite_mc = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ai4BKQgIAAgGgFQgGgGABgIIAAhsQgBgJAGgGQAGgGAIABIFwAAQAJgBAGAGQAFAGAAAJIAABsQAAAIgFAGQgGAFgJAAg");
	this.shape.setTransform(138.3,4.3,0.23,0.23);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AjBBkQgPAAgLgLQgKgKABgOIAAiAQgBgPAKgKQALgKAPAAIGDAAQAPAAAKAKQALAKAAAPIAACAQAAAOgKAKIgBABQgKAKgPAAgAjThRIAAAAQgIAHAAALIAACAQAAAKAIAHQAHAIALAAIGDAAQALAAAHgIQAHgHABgKIAAiAQgBgLgHgHQgHgIgLABImDAAQgLgBgHAIg");
	this.shape_1.setTransform(138.3,4.3,0.23,0.23);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgoAsQAUgQAUAAQAVAAATAQIgoAugAAAAAQghAAgbAWIgTgWQAjgdAsAAQAtAAAjAdIgUAWQgagWgiAAgAAAg6Qg5AAgrAlIgSgUQA2gwBAABQBAgBA3AwIgTAUQgqglg6AAg");
	this.shape_2.setTransform(20.7,4.1,0.235,0.235);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("ADwAnQgQgRAAgWQAAgVAQgRQAQgPAYgBQAWABARAPQAQARAAAVQAAAWgQARQgRAPgWAAQgYAAgQgPgABlAnQgRgRABgWQgBgVARgRQAPgPAYgBQAWABAQAPQAQARAAAVQAAAWgQARQgQAPgWAAQgYAAgPgPgAgmAnQgQgRAAgWQAAgVAQgRQARgPAVgBQAWABARAPQAQARAAAVQAAAWgQARQgRAPgWAAQgVAAgRgPgAiyAnQgQgRABgWQgBgVAQgRQARgPAXgBQAWABAQAPQAQARAAAVQAAAWgQARQgQAPgWAAQgXAAgRgPgAk+AnQgQgRAAgWQAAgVAQgRQARgPAWgBQAXABARAPQAPARAAAVQAAAWgPARQgRAPgXAAQgWAAgRgPg");
	this.shape_3.setTransform(7.9,4.2,0.235,0.235);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgCgHQACAAABADQACACAAACQAAADgCACQgBADgCAAg");
	this.shape_4.setTransform(144.4,4.2);

	// 8:50 PM
	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgPAVIgDgCIgEgFIgDgHIAAgHIAAgGIADgHIACgDIACgDIADgBIAEAAQAFAAADABIACADIABADIABAHIABAGIgBAHIgBAHIgDAFQgDADgFAAIgEgBgAgOgNIgDADIgBAGIAAAEIAAAGIABAFIADAEIADAAIAEAAIADgEIABgFIAAgGIAAgEIgBgGIgDgDIgEgCIgDACgAgyAVIgFgDIgDgEQgBgDAAgDIAHAAQAAAEACACIACABIADAAIAEAAIADgCIABgDIAAgEIAAgDIgCgDIgCAAIgEgBIgEABIgDABIgGAAIAEgUIAWAAIAAAGIgRAAIgCALIAEgDIAEgBQADAAADACIAEACIACACIABAGIgBAGIgCAEIgFAEIgDABIgDABIgGgBgAhlAVIgFgDIgDgEIgBgGQAAgEACgDIACgBIADAAIgEgDQgCgDAAgDQAAgGAEgDIAEgBIAFgBIAGABIAEABIADAFIABAEQAAADgCADIgEADQADAAACABQACADAAAEIgBAGIgDAEIgFADIgGABIgFgBgAhjABIgCACIgCACIgBADIABAEIACACQACACADAAIAEgBIACgBQACgCAAgEQAAgEgCgBIgCgCIgEAAIgDAAgAhkgNIgCACIAAACQAAABAAABQAAABAAAAQABABAAAAQAAABABAAIACACIACAAQADgBACgBIACgCIAAgDQAAgCgCgCQgCgCgDAAQAAAAgBAAQgBAAAAAAQgBABAAAAQgBAAAAABgABoAVIAAgfIgMAfIgGAAIgMgfIAAAfIgHAAIAAgpIAKAAIAMAfIAMgfIAKAAIAAApgAAaAVIAAgpIATAAIAEAAIAEABIAEADIACAFIABAEIgBAEIgCADIgEADIgEABIgEAAIgLAAIAAARgAAiAAIALAAIACgBIADAAIACgCIAAgEIAAgDIgCgDIgCgBIgOAAgAhKAVIAAgIIAIAAIAAAIgAhKAAIAAgIIAIAAIAAAIg");
	this.shape_5.setTransform(71.4,4.3);

	this.addChild(this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,2,144.8,4.6);


(lib.statusBar_mc = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#232021").s().p("Ai4BKQgIAAgGgFQgGgGABgIIAAhsQgBgJAGgGQAGgGAIABIFwAAQAJgBAGAGQAFAGAAAJIAABsQAAAIgFAGQgGAFgJAAg");
	this.shape.setTransform(138.3,4.3,0.23,0.23);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#232021").s().p("AjBBkQgPAAgLgLQgKgKABgOIAAiAQgBgPAKgKQALgKAPAAIGDAAQAPAAAKAKQALAKAAAPIAACAQAAAOgKAKIgBABQgKAKgPAAgAjThRIAAAAQgIAHAAALIAACAQAAAKAIAHQAHAIALAAIGDAAQALAAAHgIQAHgHABgKIAAiAQgBgLgHgHQgHgIgLABImDAAQgLgBgHAIg");
	this.shape_1.setTransform(138.3,4.3,0.23,0.23);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#232021").s().p("AgoAsQAUgQAUAAQAVAAATAQIgoAugAAAAAQghAAgbAWIgTgWQAjgdAsAAQAtAAAjAdIgUAWQgagWgiAAgAAAg6Qg5AAgrAlIgSgUQA2gwBAABQBAgBA3AwIgTAUQgqglg6AAg");
	this.shape_2.setTransform(20.7,4.1,0.235,0.235);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#232021").s().p("ADwAnQgQgRAAgWQAAgVAQgRQAQgPAYgBQAWABARAPQAQARAAAVQAAAWgQARQgRAPgWAAQgYAAgQgPgABlAnQgRgRABgWQgBgVARgRQAPgPAYgBQAWABAQAPQAQARAAAVQAAAWgQARQgQAPgWAAQgYAAgPgPgAgmAnQgQgRAAgWQAAgVAQgRQARgPAVgBQAWABARAPQAQARAAAVQAAAWgQARQgRAPgWAAQgVAAgRgPgAiyAnQgQgRABgWQgBgVAQgRQARgPAXgBQAWABAQAPQAQARAAAVQAAAWgQARQgQAPgWAAQgXAAgRgPgAk+AnQgQgRAAgWQAAgVAQgRQARgPAWgBQAXABARAPQAPARAAAVQAAAWgPARQgRAPgXAAQgWAAgRgPg");
	this.shape_3.setTransform(7.9,4.2,0.235,0.235);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#232021").s().p("AgCgHQACAAABADQACACAAACQAAADgCACQgBADgCAAg");
	this.shape_4.setTransform(144.4,4.2);

	// 8:50 PM
	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#232021").s().p("AgPAVIgDgCIgEgFIgDgHIAAgHIAAgGIADgHIACgDIACgDIADgBIAEAAQAFAAADABIACADIABADIABAHIABAGIgBAHIgBAHIgDAFQgDADgFAAIgEgBgAgOgNIgDADIgBAGIAAAEIAAAGIABAFIADAEIADAAIAEAAIADgEIABgFIAAgGIAAgEIgBgGIgDgDIgEgCIgDACgAgyAVIgFgDIgDgEQgBgDAAgDIAHAAQAAAEACACIACABIADAAIAEAAIADgCIABgDIAAgEIAAgDIgCgDIgCAAIgEgBIgEABIgDABIgGAAIAEgUIAWAAIAAAGIgRAAIgCALIAEgDIAEgBQADAAADACIAEACIACACIABAGIgBAGIgCAEIgFAEIgDABIgDABIgGgBgAhlAVIgFgDIgDgEIgBgGQAAgEACgDIACgBIADAAIgEgDQgCgDAAgDQAAgGAEgDIAEgBIAFgBIAGABIAEABIADAFIABAEQAAADgCADIgEADQADAAACABQACADAAAEIgBAGIgDAEIgFADIgGABIgFgBgAhjABIgCACIgCACIgBADIABAEIACACQACACADAAIAEgBIACgBQACgCAAgEQAAgEgCgBIgCgCIgEAAIgDAAgAhkgNIgCACIAAACQAAABAAABQAAABAAAAQABABAAAAQAAABABAAIACACIACAAQADgBACgBIACgCIAAgDQAAgCgCgCQgCgCgDAAQAAAAgBAAQgBAAAAAAQgBABAAAAQgBAAAAABgABoAVIAAgfIgMAfIgGAAIgMgfIAAAfIgHAAIAAgpIAKAAIAMAfIAMgfIAKAAIAAApgAAaAVIAAgpIATAAIAEAAIAEABIAEADIACAFIABAEIgBAEIgCADIgEADIgEABIgEAAIgLAAIAAARgAAiAAIALAAIACgBIADAAIACgCIAAgEIAAgDIgCgDIgCgBIgOAAgAhKAVIAAgIIAIAAIAAAIgAhKAAIAAgIIAIAAIAAAIg");
	this.shape_5.setTransform(71.4,4.3);

	this.addChild(this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,2,144.8,4.6);


(lib.startMenu_mc = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AAWAgIgWgWIgUAWQgCACgEAAQgDAAgBgCQgDgCAAgDQAAgEADgCIAVgVIgVgUQgDgCAAgDQAAgEADgCQABgCADAAQAEAAACACIAUAWIAWgWQABgCADAAQAEAAACACQACACAAAEQAAADgCACIgWAUIAWAVQACACAAAEQAAADgCACQgCACgEAAQgDAAgBgCg");
	this.shape.setTransform(3.5,5.8);

	// EDIT
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#232021").s().p("AAqAdIAAgwIgJAAIAAgJIAdAAIAAAJIgKAAIAAAwgAAPAdIAAg5IAKAAIAAA5gAgYAdIAAg5IAOAAQAEAAADACIADADQAEAEgBAJIAAAVQABAJgEAEQAAADgDABIgHABgAgPAVIADAAQAEAAACgCQACgCAAgFIAAgXQAAgEgCgDQgCgBgEAAIgDAAgAg9AdIAAg5IAbAAIAAAJIgRAAIAAAPIANAAIAAAHIgNAAIAAARIASAAIAAAJg");
	this.shape_1.setTransform(128.2,6.8);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,2.3,134.4,7.4);


(lib.reel_mc = function() {
	this.initialize();

	// txt
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AFxT3QgGgDgDgEQgEgEgCgGQgCgFAAgHIASgCQABAIADAEQADAFAFAAQAEAAAEgDQADgDAAgFQAAgFgDgFIgHgIIgKgIIgJgJQgEgFgDgGQgDgGAAgIQAAgHACgFQABgFAEgEQAIgHAPAAQAFAAAFACQAEACAEAEQADAEADAFQABAEABAGIgSACIgBgGIgDgDIgDgCIgDgBQgFAAgCADQgDADAAAFQAAAFADAEIAHAIIAKAIIAJAJQAFAFACAGQADAGAAAIQAAAHgCAFQgDAFgDAEQgEAEgGABQgGACgGAAQgHAAgFgCgAA5T3QgGgCgDgEQgDgEgCgFIgCgLIAAg6IACgLQACgFADgEQADgEAGgCQAGgDAHAAQAIAAAGADQAFACAEAEQADAEACAFIABALIAAA6IgBALQgCAFgDAEQgEAEgFACQgGACgIAAQgHAAgGgCgAA+SaQgCADAAAGIAAA5QAAAGACAEQADADAFAAQAGAAACgDQACgEAAgGIAAg5QAAgGgCgDQgCgDgGAAQgFAAgDADgAhaT3QgFgDgEgEQgDgEgDgGQgCgFAAgHIASgCQABAIAEAEQADAFAEAAQAFAAADgDQADgDABgFQAAgFgEgFIgHgIIgJgIIgJgJQgFgFgDgGQgDgGAAgIQAAgHACgFQACgFAEgEQAHgHAPAAQAGAAAFACQAEACAEAEQADAEACAFQACAEABAGIgSACIgCgGIgDgDIgCgCIgEgBQgFAAgCADQgDADAAAFQABAFADAEQACAEAFAEIAJAIIAKAJQAEAFACAGQAEAGAAAIQAAAHgCAFQgDAFgEAEQgEAEgFABQgGACgHAAQgHAAgFgCgAosT3QgGgCgDgEQgDgEgCgFIgCgLIAAg6IACgLQACgFADgEQADgEAGgCQAFgDAJAAQAHAAAFADQAGACADAEQAEAEACAFIACALIAAA6IgCALQgCAFgEAEQgDAEgGACQgFACgHAAQgJAAgFgCgAonSaQgCADAAAGIAAA5QAAAGACAEQADADAGAAQAFAAADgDQACgEAAgGIAAg5QAAgGgCgDQgDgDgFAAQgGAAgDADgApwT5IAAgQIAEAAQAFAAADgDQACgCAAgFIAAhXIATAAIAABZQAAAGgBAEQgBAFgDADQgDADgFACQgFABgJAAgAG0T4IAAhfIgSAAIAAgRIA4AAIAAARIgTAAIAABfgAE8T4IAAhwIAUAAIAABwgAD9T4IAAhwIATAAIAABfIAfAAIAAARgADNT4IAAhfIgTAAIAAgRIA5AAIAAARIgTAAIAABfgACgT4IgNgvIgLABIAAAuIgTAAIAAhwIAbAAQAIAAAHACQAFACAEADQAJAIAAASQAAAHgBAEIgEAJIgEAFIgFADIAQAzgACIS6IAHAAIAHgBIAEgCIADgGIABgIQAAgKgEgEQgBgCgDAAIgHgBIgHAAgAAET4IAAgyIgTAAIAAAyIgTAAIAAhwIATAAIAAAtIATAAIAAgtIATAAIAABwgAjNT4IAAhwIA0AAIAAARIghAAIAAAcIAZAAIAAARIgZAAIAAAhIAjAAIAAARgAjyT4IAAgyIgUAAIAAAyIgTAAIAAhwIATAAIAAAtIAUAAIAAgtIATAAIAABwgAlKT4IAAhfIgTAAIAAgRIA5AAIAAARIgTAAIAABfgAmbT4IgYhGIAAAAIAABGIgRAAIAAhwIARAAIAXBAIABAAIAAhAIARAAIAABwgAntT4IAAhwIATAAIAABwgAmfRrQgEgCgDgEIgDgKIgBgQIABgPIADgLQADgEAEgBQADgCAFAAQADAAADABQADABACADIADAGIACAJIgHAAIgBgGIgCgFIgDgCIgDgBQgDAAgDABIgDAFIgCAIIgCANIACANIACAJIADAEQADACADAAIAEgBIADgDIACgFIABgIIAHAAQAAAGgBAEIgEAHIgFAEQgDACgEAAQgFAAgDgCgAjMRsIAAgcIgPglIAIAAIALAcIAKgcIAIAAIgPAlIAAAcgAjlRsIAAg8IgOA8IgEAAIgOg8IAAA8IgHAAIAAhBIAMAAIALAxIALgxIALAAIAABBgAkwRsIAAhBIAeAAIAAAGIgXAAIAAAWIARAAIAAAGIgRAAIAAAZIAYAAIAAAGgAlZRsIAAhBIALAAQAGAAADABIAEACIAEAEIACAEIACAGIABAPIgBAQIgCAGIgCAEIgEADIgEACQgDACgGAAgAlTRmIAEAAIAHgBQADgBACgDQACgDACgFIABgOIgBgNQgCgFgCgDQgCgDgDgBIgHgBIgEAAgAllRsIgDgTIgRAAIgDATIgIAAIAPhBIAKAAIANBBgAl4RTIAPAAIgIgjgAmzRsIgEgTIgRAAIgEATIgHAAIAPhBIAKAAIANBBgAnHRTIAPAAIgIgjgAoDRsIAAhBIAdAAIAAAGIgWAAIAAAWIAQAAIAAAGIgQAAIAAAZIAXAAIAAAGgAoORsIgMgjIgJAPIAAAUIgGAAIAAhBIAGAAIAAAhIABAAIASghIAHAAIgMAWIAPArgAo5RsIAAhBIAHAAIAABBgApJRsIgUg5IAAAAIAAA5IgIAAIAAhBIALAAIARAwIAAAAIAAgwIAIAAIAABBgAFFwrQgDgEgCgFQgBgGAAgGIAAg6IABgLQACgFADgEQAEgEAFgCQAFgDAIAAQAGAAAGADQAFACAEAEQAEAFACAFQABAGAAAGIAAAHIgSAAIAAgKIgCgHIgEgDIgFgBQgDAAgDADQgDACABAHIAAA6QAAAFABADQACAEAGAAQAGAAACgEQACgEAAgIIAAgLIgMAAIAAgPIAfAAIAAA5IgJAAIgDgJQgFAFgEADQgEACgHAAQgLAAgIgHgAJfwlIgOgpIgNApIgTAAIAWg7IgVg1IATAAIAMAjIALgjIATAAIgUA1IAWA7gAIPwlIAAhwIATAAIAABwgAHrwlIAAhYIgRBYIgKAAIgRhYIAAAAIAABYIgSAAIAAhwIAaAAIANBBIABAAIAOhBIAZAAIAABwgAEcwlIgZhGIgBAAIAABGIgRAAIAAhwIASAAIAYBAIAAAAIAAhAIARAAIAABwgADJwlIAAhwIATAAIAABwgACjwlIgYhGIgBAAIAABGIgRAAIAAhwIASAAIAXBAIAAAAIAAhAIARAAIAABwgABQwlIAAhwIATAAIAABwgAAwwlIgEgZIgUAAIgEAZIgTAAIAVhwIAYAAIAVBwgAAaxPIAQAAIgIgwgAgYwlIgNgvIgKABIAAAuIgTAAIAAhwIAbAAQAIAAAGACQAGACAEADQAJAIgBASQAAAHgBAEIgDAJIgFAFIgEADIAQAzgAgvxjIAHAAIAGgBIAFgCIACgGIABgIQAAgKgDgEQgCgCgDAAIgGgBIgHAAgAh0wlIAAhfIgSAAIAAgRIA4AAIAAARIgTAAIAABfgAjFwlIgNgvIgKABIAAAuIgTAAIAAhwIAbAAQAIAAAGACQAGACAEADQAIAIAAASQABAHgCAEIgDAJIgFAFIgEADIAQAzgAjcxjIAHAAIAGgBIAFgCIADgGIAAgIQAAgKgDgEQgCgCgDAAIgGgBIgHAAgAkNwlIgDgZIgVAAIgEAZIgSAAIAUhwIAYAAIAVBwgAkixPIAPAAIgHgwgAlVwlIAAhYIgSBYIgJAAIgRhYIgBAAIAABYIgRAAIAAhwIAaAAIAOBBIAAAAIANhBIAaAAIAABwgAnGwlIAAgvIgYhBIAUAAIAOAqIAAAAIANgqIATAAIgXBBIAAAvgAoawlIAAhwIAzAAIAAARIggAAIAAAcIAZAAIAAARIgZAAIAAAhIAiAAIAAARgAo9wlIgYhGIgBAAIAABGIgRAAIAAhwIASAAIAXBAIAAAAIAAhAIARAAIAABwgAgiy3QgDgCgCgEIgEgKIgCgQIACgPIAEgLQACgDADgCQAEgCAEAAQAEAAADACQAEACADADIADALIABAPIgBAQIgDAKQgDAEgEACQgDACgEAAQgEAAgEgCgAgezxIgEAEIgDAJIAAANIAAAOIADAIIAEAFIAEABIAFgBIADgFIACgIIABgOIgBgNIgCgJIgDgEIgFgBIgEABgAhLy3QgDgCgDgEIgDgKIgCgQIACgPIADgLQADgDADgCQADgCAFAAQAEAAADACQADACADADIADALIACAPIgCAQIgDAKQgDAEgDACQgDACgEAAQgFAAgDgCgAhIzxIgDAEIgDAJIgBANIABAOIADAIIADAFIAFABIAEgBIADgFIADgIIABgOIgBgNIgDgJIgDgEIgEgBIgFABgAiky3QgEgCgDgEIgDgKIgBgQIABgPIADgLQADgDAEgCQADgCAEAAQAEAAADACQAEACACADIAEALIACAPIgCAQIgEAKQgCAEgEACQgDACgEAAQgEAAgDgCgAiizxIgDAEIgDAJIgBANIABAOIADAIIADAFIAFABIAEgBIAEgFIADgIIABgOIgBgNIgDgJIgEgEIgEgBIgFABgAkiy3QgEgCgDgEIgDgKIgBgQIABgPIADgLQADgEAEgBQADgCAFAAQADAAADABQADABACADIADAGIACAJIgHAAIgBgGIgCgFIgDgCIgDgBQgEAAgCABIgDAFIgDAIIgBANIABANIADAJIADAEQACACAEAAIAEgBIADgDIACgFIABgIIAHAAQAAAGgCAEIgDAHIgFAEQgDACgEAAQgFAAgDgCgAoMy3QgDgBgDgCIgCgGIgBgHIAAgwIAHAAIAAAvQAAAHACACIACADIAFABIAEgBIADgDQACgCABgHIAAgvIAGAAIAAAwIgBAHIgDAGQgBACgEABQgDACgEAAQgEAAgDgCgAo2y3QgEgCgCgEIgEgKIgBgQIABgPIAEgLQACgDAEgCQAEgCADAAQAEAAAEACQAEACACADIAEALIABAPIgBAQIgEAKQgCAEgEACQgEACgEAAQgDAAgEgCgAozzxIgEAEIgCAJIgBANIABAOIACAIIAEAFIAEABIAFgBIAEgFIACgIIABgOIgBgNIgCgJIgEgEIgFgBIgEABgApcy3QgDgBgDgCIgDgGIgBgIIAGAAIABAFIACAEIADADIAFABIAEgBIADgCIACgDIABgFIgBgFIgEgEIgJgHIgEgEIgFgEIgDgFIAAgGIAAgGQACgDACgCIAFgDIAGgBQADAAADABIAGADIACAGQACADAAAEIgGAAIgBgEIgCgEIgDgCIgEgBIgEAAIgDACQgCADAAADIABAFIADAEIAJAHIAJAIIACAFQACADAAAEIgCAHIgDAFIgFAEIgHABQgDAAgDgCgACKy2IAAhBIAHAAIAAA7IAVAAIAAAGgABqy2IAAhBIAIAAIAAA7IAUAAIAAAGgABgy2IgDgTIgRAAIgEATIgHAAIAOhBIAKAAIAOBBgABNzPIAOAAIgHgjgAAcy2IAAhBIARAAIAHABIAFADIADAFIABAHIgBAEIgBAFIgEADIgEACIAFADIAEADIACAFIAAAGQABAEgCAEQgBADgCACQgDADgEABIgJABgAAjy8IAIAAIAFgBIAEgCQABgBAAAAQAAAAABgBQAAAAAAgBQAAAAAAgBIABgFIgBgGIgCgEIgDgDIgGAAIgIAAgAAjzbIAFAAIAGgBIAFgCQAAAAAAgBQABAAAAAAQAAgBABgBQAAAAAAgBIABgFIgBgFIgCgDIgDgCIgFAAIgIAAgAAFy2IAAg7IgMAAIAAgGIAgAAIAAAGIgNAAIAAA7gAh0y2IAAhBIAcAAIAAAGIgVAAIAAAWIAQAAIAAAGIgQAAIAAAfgAjFy2IAAg7IgNAAIAAgGIAhAAIAAAGIgNAAIAAA7gAjoy2IgMgjIgIAPIAAAUIgHAAIAAhBIAHAAIAAAhIAAAAIASghIAIAAIgMAWIAOArgAk2y2IgEgTIgRAAIgDATIgHAAIAOhBIAKAAIAOBBgAlKzPIAPAAIgHgjgAlfy2IgKgfIgJAAIAAAfIgIAAIAAhBIAQAAIAIABQADABACACQADACABADQABAEAAAEIAAAFIgCAEIgEAEIgEADIALAggAlyzbIAGAAIAGgBIAEgCIACgDIABgFIgBgFQAAAAAAgBQgBAAAAgBQAAAAAAgBQgBAAAAAAIgEgDIgGAAIgGAAgAmRy2IAAg7IgOAAIAAgGIAjAAIAAAGIgOAAIAAA7gAnDy2IAAhBIAMAAQAGAAADABIAFACIACAEIADAEIACAGIACAPIgCAQIgCAGIgDAEIgCADIgFACQgDACgGAAgAm7y8IADAAIAHgBQADgBACgDQACgDACgFIABgOIgBgNQgCgFgCgDQgCgDgDgBIgHgBIgDAAgAnSy2IgUg5IAAAAIAAA5IgHAAIAAhBIALAAIAQAwIABAAIAAgwIAHAAIAABBg");
	this.shape.setTransform(68.6,400.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("ACDDEQgIgIAAgPIAAhXIAUAAIAABXQAAANALAAQAKAAAAgNIAAhXIAUAAIAABXQAAAHgCAGQgCAGgEAEQgIAHgOAAQgOAAgJgHgABFDJQgFgDgEgEQgEgFgCgFQgCgGAAgHIATgCQAAAIADAFQAEAEAEAAQAGAAADgDQADgCAAgFQAAgGgDgFIgHgIIgKgJIgKgJQgEgFgDgGQgDgGAAgJQAAgHACgFQACgFAEgEQAIgHAOAAQAGAAAFACQAFACAEAEIAFAIQACAGABAGIgTACIgBgGIgDgEIgDgCIgEgBQgEAAgDADQgCADAAAFQAAAFACAEIAIAJIAKAIIAJAJQAFAGADAGQADAGAAAIQAAAHgCAFQgDAGgEAEQgEADgGACQgGACgHAAQgGAAgGgCgAkXDEQgIgIAAgPIAAhXIAUAAIAABXQAAANAKAAQALAAAAgNIAAhXIAUAAIAABXQAAAHgCAGQgCAGgEAEQgJAHgOAAQgOAAgIgHgAlaDJQgFgCgEgEQgEgEgCgGQgCgFAAgGIAAg8QAAgGACgFQACgGAEgEQAEgEAFgCQAGgCAIAAQAHAAAGACQAFADAEAEQAEAEABAGQACAGAAAGIAAAJIgUAAIAAgJQAAgIgDgDQgCgDgEAAQgGAAgDADQgCADAAAHIAAA6QAAAHACADQADADAGAAQAFAAACgDQACgDAAgGIAAgNIAUAAIAAANQAAAGgCAFQgBAGgEAEQgEAEgFACQgGACgHAAQgIAAgGgCgAIsDKIAAgwIgYhEIAVAAIANAsIABAAIANgsIAUAAIgYBEIAAAwgAHiDKIAAh0IAUAAIAABiIAfAAIAAASgAGgDKIAAh0IA4AAIAAASIgkAAIAAAdIAbAAIAAASIgbAAIAAAzgAGBDKIgOgwIgKAAIAAAwIgUAAIAAh0IAcAAQAIAAAGACQAHACAEAEQAIAIAAASIgBAMIgDAJIgFAFIgFADIARA1gAFpCKIAHAAIAHgBIAEgDIADgFIAAgJQAAgKgDgEIgEgDIgHAAIgHAAgAESDKIAAh0IA1AAIAAASIghAAIAAAdIAaAAIAAASIgaAAIAAAhIAkAAIAAASgADHDKIAAh0IAcAAQAKAAAGACQAHACAEAEQAJAIAAASQAAAKgCAGQgCAHgFAEQgEAEgHACQgHABgJAAIgIAAIAAAwgADbCKIAHAAIAIgBQAEgBACgCQACgCABgDIAAgJIAAgIQgBgEgCgCQgCgCgEgBIgIAAIgHAAgAgfDKIAAh0IAUAAIAABiIAdAAIAAASgAg4DKIgDgaIgWAAIgEAaIgTAAIAVh0IAZAAIAVB0gAhOCfIAQAAIgIgygAiFDKIAAh0IATAAIAAB0gAinDKIgPgwIgKAAIAAAwIgUAAIAAh0IAcAAQAJAAAGACQAGACAEAEQAJAIAAASIgBAMIgEAJIgEAFIgFADIARA1gAjACKIAHAAIAHgBIAFgDIACgFIABgJQAAgKgDgEIgFgDIgHAAIgHAAgAmKDKIgOgwIgKAAIAAAwIgUAAIAAh0IAcAAQAIAAAGACQAHACAEAEQAIAIAAASIgBAMIgDAJIgFAFIgFADIARA1gAmiCKIAHAAIAHgBIAEgDIADgFIAAgJQAAgKgDgEIgEgDIgHAAIgHAAgAn5DKIAAh0IA1AAIAAASIghAAIAAAdIAaAAIAAASIgaAAIAAAhIAkAAIAAASgAoYDKIAAhaIAAAAIgSBaIgKAAIgShaIAABaIgRAAIAAh0IAaAAIAOBEIAAAAIAOhEIAaAAIAAB0gAkRA4QgDgBgCgCIgDgGIgBgIIAGAAIABAFIACAEIADADIAFABIAEgBIADgCIACgDIAAgFIgBgFIgDgEIgJgHIgFgEIgEgEIgDgFIgBgGIABgGQABgBADgCIAEgDIAHgBQADAAADABIAFADIADAEQACADAAAEIgHAAIAAgEIgCgEIgDAAIgFgBIgDAAIgDABQgDACAAADIACAFIADAEIAJAHIAJAIIACAFQACADAAAEIgCAHIgDAFIgFAEIgHABQgEAAgDgCgAmaA4QgDgBgDgCIgDgGIgBgIIAGAAIABAFIACAEIAEADIAEABIAEgBIADgCIACgDIABgFIgBgFIgDgEIgJgHIgFgEIgEgEIgDgFIgBgGIABgGQABgBACgCIAFgDIAGgBQAEAAADABIAFADIADAEQABADAAAEIgGAAIgBgEIgCgEIgDAAIgEgBIgEAAIgDABQgCACAAADIABAFIADAEIAJAHIAJAIIADAFQABADAAAEIgBAHIgDAFIgFAEIgIABQgDAAgDgCgAnBA4QgDgCgDgEIgDgKIgCgQIACgPIADgJQADgDADgCQAEgCAEAAQAEAAADACQAEACACADIAEAJIABAPIgBAQIgEAKQgCAEgEACQgDACgEAAQgEAAgEgCgAm+AAIgDACIgDAJIgBANIABAOIADAIIADAFIAFABIAEgBIAEgFIACgIIABgOIgBgNIgCgJIgEgCIgEgBIgFABgAiKA5IAAg/IAMAAQAGAAADABIAEACIADADIADADIACAGIABAPIgBAQIgCAGIgDAEIgDADIgEACQgDACgGAAgAiDAzIAEAAIAHgBQADgBACgDQACgDABgFIABgOIgBgNQgBgFgCgDQgCgDgDAAIgHAAIgEAAgAitA5IAAg/IAdAAIAAAGIgWAAIAAAUIAQAAIAAAGIgQAAIAAAZIAXAAIAAAGgAjRA5IAAg/IAeAAIAAAGIgXAAIAAAUIARAAIAAAGIgRAAIAAAZIAYAAIAAAGgAj1A5IAAg/IAPAAIAHABQADABADADIADADIABAIIgBAHIgDAGIgGADIgHABIgIAAIAAAegAjuAVIAHAAIAFAAIADgCIADgEIAAgFIAAgGIgDgDIgDgBIgFAAIgHAAgAlLA5IAAg/IAeAAIAAAGIgXAAIAAAUIARAAIAAAGIgRAAIAAAZIAYAAIAAAGgAlkA5IgPg/IAHAAIAMAxIALgxIAHAAIgPA/gAl9A5IAAg/IAHAAIAAA/gAnoA5IAAg/IAHAAIAAA5IAVAAIAAAGgAoNA5IAAg/IAQAAIAHABQADABACADIAEADIABAIIgBAHIgEAGIgFADIgHABIgJAAIAAAegAoGAVIAIAAIAEAAIAEgCIACgEIABgFIgBgGIgCgDIgEgBIgEAAIgIAAgAoWA5IgMgbIgKAbIgIAAIAOgjIgNgcIAHAAIAKAVIAJgVIAIAAIgNAcIAPAjgApTA5IAAg/IAeAAIAAAGIgXAAIAAAUIARAAIAAAGIgRAAIAAAZIAYAAIAAAGgABsiJQgDgBgCgCQgCgCgBgEIgBgGIAAghIABgHQABgDACgCQACgDADgBQADgBAFAAQAEAAADABQAEABACADQACACABADIABAHIAAAhIgBAGQgBAEgCACQgCACgEABQgDACgEAAQgFAAgDgCgABvi/QgBACAAAEIAAAhQAAADABACQABABAAAAQAAAAABAAQAAABABAAQABAAABAAQABAAAAAAQABAAABgBQAAAAABAAQAAAAAAgBQACgCAAgDIAAghQAAgEgCgCQAAAAAAAAQgBgBAAAAQgBAAgBAAQAAAAgBAAQgBAAgBAAQgBAAAAAAQgBAAAAABQAAAAgBAAgABAiJQgDgBgCgCQgCgCgBgEIgBgGIAAghIABgHQABgDACgCQACgDADgBQADgBAFAAQAEAAADABQAEABACADQACACABADIABAHIAAAhIgBAGQgBAEgCACQgCACgEABQgDACgEAAQgFAAgDgCgABDi/QgBACAAAEIAAAhQAAADABACQABABAAAAQAAAAABAAQAAABABAAQABAAABAAQABAAAAAAQABAAABgBQAAAAABAAQAAAAAAgBQACgCAAgDIAAghQAAgEgCgCQAAAAAAAAQgBgBAAAAQgBAAgBAAQAAAAgBAAQgBAAgBAAQgBAAAAAAQgBAAAAABQAAAAgBAAgAEliIIAAhBIALAAIAAA3IASAAIAAAKgAEDiIIAAhBIALAAIAAA3IASAAIAAAKgADziIIgCgPIgMAAIgCAPIgLAAIAMhBIAOAAIAMBBgADnigIAJAAIgFgcgACxiIIAAhBIAQAAIAIABQADABACACQACACABAEIABAHIAAAEIgBAEIgDADIgDADIAEACIACADQADAEAAAGIgBAHIgDAGQgCADgEABQgDACgFAAgAC8iRIAEAAQAFAAACgDQACgCAAgFQAAgFgCgDQgDgCgFAAIgDAAgAC8ivIAEAAQADAAACgCQACgCAAgEQAAgJgHAAIgEAAgACViIIAAg3IgLAAIAAgKIAhAAIAAAKIgLAAIAAA3gAAQiIIAAhBIAfAAIAAAKIgUAAIAAAQIAPAAIAAAKIgPAAIAAAdgAgoiIIAAhBIAeAAIAAAKIgTAAIAAAQIAOAAIAAAKIgOAAIAAATIAUAAIAAAKgAg3iIIgKgeIgEAHIAAAXIgLAAIAAhBIALAAIAAAYIAMgYIALAAIgMAYIAOApgAhmiIIAAhBIALAAIAABBgAh7iIIgOgpIAAApIgKAAIAAhBIAKAAIAOAlIAAglIAKAAIAABBg");
	this.shape_1.setTransform(66.9,36.8);

	// header shape
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AryAxIAAhiIXlAAIAABig");
	this.shape_2.setTransform(75.5,5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AryBeIAAi8IXlAAIAAC8g");
	this.shape_3.setTransform(75.5,19.5);

	// Layer 1
	this.instance = new lib.reel();
	this.instance.setTransform(0,29);

	this.addChild(this.instance,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,151,727);


(lib.newMessage_mc = function() {
	this.initialize();

	// newMessageContainer_mc
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#D2D2D2").s().p("AieCCIg8AAIAAldIG1AAIAAFdIkHAAIhyBag");
	this.shape.setTransform(76.5,20.5,0.159,0.159);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AryCvIAAldIXlAAIAAFdg");
	this.shape_1.setTransform(75.5,17.5);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,151,35);


(lib.menuBar2_mc = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#232021").s().p("AifCQIAAgxIE/AAIAAAxgAifAZIAAgxIE/AAIAAAxgAifhdIAAgzIE/AAIAAAzg");
	this.shape.setTransform(3.8,3.4,0.235,0.235);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,7.5,6.8);


(lib.menuBar_mc = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#232021").s().p("AB8AjQgOgPAAgUQAAgUAOgOQAPgPAUAAQAVAAAPAPQAPAOAAAUQAAAUgPAPQgPAOgVAAQgUAAgPgOgAgiAjQgPgPAAgUQAAgUAPgOQAOgPAUAAQAUAAAPAPQAOAOAAAUQAAAUgOAPQgPAOgUAAQgUAAgOgOgAjCAjQgPgPAAgUQAAgUAPgOQAOgPAWAAQAUAAAPAPQAOAOAAAUQAAAUgOAPQgPAOgUAAQgWAAgOgOg");
	this.shape.setTransform(129.9,3.5,0.235,0.235);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#232021").s().p("AifCQIAAgxIE/AAIAAAxgAifAZIAAgxIE/AAIAAAxgAifhdIAAgzIE/AAIAAAzg");
	this.shape_1.setTransform(3.8,3.4,0.235,0.235);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,134.9,6.8);


(lib.member_3_mc = function() {
	this.initialize();

	// member_big_3.png
	this.instance = new lib.member_big_3();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,32,32);


(lib.member_2_mc = function() {
	this.initialize();

	// member_big_2.png
	this.instance = new lib.member_big_2();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,32,32);


(lib.member_1_mc = function() {
	this.initialize();

	// member_big_1.png
	this.instance = new lib.member_big_1();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,32,32);


(lib.footer_4_mc = function() {
	this.initialize();

	// txt
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AhLAjQgGgFAAgLIAAg5IANAAIAAA6QAAAIAIAAQAHAAAAgIIAAg6IAOAAIAAA5QAAAFgCAEQgBAEgCADQgGAFgKAAQgKAAgFgFgAh7AnQgDgCgDgDQgDgCgBgEQgBgEAAgEIAAgnQAAgEABgEQABgEADgCQADgDADgCQAEgBAFAAQAGAAAEABQADACADADQADACABAEQACAEAAAEIAAAnQAAAEgCAEQgBAEgDACQgDADgDACQgEABgGAAQgFAAgEgBgAh3gZQgCACAAAEIAAAnQAAAEACACQABACAEAAQAFAAABgCQACgCAAgEIAAgnQAAgEgCgCQgBgCgFAAQgEAAgBACgACxAnIgSgvIAAAvIgNAAIAAhNIANAAIARArIAAgrIAMAAIAABNgAB3AnIAAhNIAOAAIAABNgAAvAnIAAhNIAkAAIAAAMIgWAAIAAAUIASAAIAAAKIgSAAIAAAXIAYAAIAAAMgAAYAnIgJghIgEABIgEAAIAAAgIgMAAIAAhNIASAAQAGAAAEABIAHAEQAGAGAAAMIgBAJIgCAFIgDACIgEACIAMAkgAAHgDIAFAAIAFAAIADgCIACgEIAAgGQAAgHgCgCIgDgCIgFgBIgFAAgAirAnIAAghIgRgsIAPAAIAJAeIABAAIAJgeIANAAIgQAsIAAAhgAgbgIIAAgeIAKAAIAAAeg");
	this.shape.setTransform(76.6,12);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#83FF60").s().p("AgLAZIAAgHIALgSIACgFIACgHQAAAAAAgBQAAgBAAAAQgBgBAAAAQAAgBgBAAQAAAAAAgBQAAAAgBAAQAAAAAAAAQgBAAAAAAQAAAAAAAAQAAAAAAAAQgBAAAAAAQAAABAAAAIgBAEIAAAEIgIAAIAAgDIAAgFIADgFIAEgCIADgBIAFAAIAEADIACAEIABAEIgBAGIgCAHIgFAGIgGAMIANAAIAAAHg");
	this.shape_1.setTransform(141.8,11.5);

	// circle
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#4B8C3A").s().p("Ah2B3QgzgxAAhGQAAhFAzgxQAxgzBFAAQBGAAAxAzQAzAxAABFQAABGgzAxQgxAzhGAAQhFAAgxgzg");
	this.shape_2.setTransform(142,11.5,0.235,0.235);

	// bg
	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#83FF60").s().p("AryBzIAAjlIXlAAIAADlg");
	this.shape_3.setTransform(75.5,11.5);

	this.addChild(this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,151,23);


(lib.footer_3_mc = function() {
	this.initialize();

	// txt
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AhLAjQgGgFAAgLIAAg5IANAAIAAA6QAAAIAIAAQAHAAAAgIIAAg6IAOAAIAAA5QAAAFgCAEQgBAEgCADQgGAFgKAAQgKAAgFgFgAh7AnQgDgCgDgDQgDgCgBgEQgBgEAAgEIAAgnQAAgEABgEQABgEADgCQADgDADgCQAEgBAFAAQAGAAAEABQADACADADQADACABAEQACAEAAAEIAAAnQAAAEgCAEQgBAEgDACQgDADgDACQgEABgGAAQgFAAgEgBgAh3gZQgCACAAAEIAAAnQAAAEACACQABACAEAAQAFAAABgCQACgCAAgEIAAgnQAAgEgCgCQgBgCgFAAQgEAAgBACgACxAnIgSgvIAAAvIgNAAIAAhNIANAAIARArIAAgrIAMAAIAABNgAB3AnIAAhNIAOAAIAABNgAAvAnIAAhNIAkAAIAAAMIgWAAIAAAUIASAAIAAAKIgSAAIAAAXIAYAAIAAAMgAAYAnIgJghIgEABIgEAAIAAAgIgMAAIAAhNIASAAQAGAAAEABIAHAEQAGAGAAAMIgBAJIgCAFIgDACIgEACIAMAkgAAHgDIAFAAIAFAAIADgCIACgEIAAgGQAAgHgCgCIgDgCIgFgBIgFAAgAirAnIAAghIgRgsIAPAAIAJAeIABAAIAJgeIANAAIgQAsIAAAhgAgbgIIAAgeIAKAAIAAAeg");
	this.shape.setTransform(76.6,12);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#83FF60").s().p("AAAAZIAAgmIgGAAIAAgEIAGgEIADgDIAEAAIAAAxg");
	this.shape_1.setTransform(141.5,11.5);

	// circle
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#4B8C3A").s().p("AgaAcQgNgMAAgQQAAgPANgLQALgNAPAAQAQAAAMANQAMALgBAPQABAQgMAMQgMAMgQgBQgPABgLgMg");
	this.shape_2.setTransform(142,11.5);

	// bg
	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#83FF60").s().p("AryBzIAAjlIXlAAIAADlg");
	this.shape_3.setTransform(75.5,11.5);

	this.addChild(this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,151,23);


(lib.footer_2_mc = function() {
	this.initialize();

	// I'M IN
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("ABcAnIgRgvIAAAvIgNAAIAAhNIANAAIARArIAAgrIAMAAIAABNgAAjAnIAAhNIAOAAIAABNgAgKAnIAAg8IgBAAIgMA8IgHAAIgMg8IAAAAIAAA8IgMAAIAAhNIASAAIAKAsIAKgsIAQAAIAABNgAhnAnIAAhNIANAAIAABNgAhMgIIAAgeIALAAIAAAeg");
	this.shape.setTransform(77,12);

	// bg
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#83FF60").s().p("AryBzIAAjlIXlAAIAADlg");
	this.shape_1.setTransform(75.5,11.5);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,151,23);


(lib.footer_1_mc = function() {
	this.initialize();

	// LET'S PLAY
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgoAnIgGgFQgDgDgBgEIgCgJIANgCQABAHABADQADACADAAQAEAAACgBQACgCAAgEQAAgEgCgDIgFgGIgHgFIgGgFIgGgHQgBgFAAgFQgBgFACgEQABgEADgCQAFgFAKAAQAFAAADABQAEACACACIADAGIACAIIgMABIgBgEIgCgDIgDgBIgCAAQgDAAgCACQgCACAAADQAAAEADADIAEAFIAIAGIAGAFIAFAHQACAFAAAFQAAAFgCAEQgBAEgDACQgDADgEABIgJABQgEAAgEgBgACuAnIAAghIgRgsIAOAAIAKAeIAAAAIAJgeIANAAIgPAsIAAAhgACPAnIgDgRIgOAAIgDARIgNAAIAPhNIAQAAIAPBNgACKAKIgFggIgFAgIAKAAgABJAnIAAhNIANAAIAABBIAWAAIAAAMgAAUAnIAAhNIATAAQAHAAAEABQAGACACACQAHAGAAAMQgBAHgBAEQgCAEgDABQgCADgGABQgEACgHAAIgGAAIAAAggAAhgDIAGAAIAGAAQAAAAABgBQAAAAABAAQAAAAAAgBQABAAAAAAQAAgBABAAQAAAAAAgBQABAAAAgBQAAAAAAgBIAAgGIAAgGIgCgDQAAgBgBAAQAAAAAAAAQgBgBAAAAQgBAAAAAAIgGgBIgGAAgAhpAnIAAhBIgNAAIAAgMIAoAAIAAAMIgOAAIAABBgAigAnIAAhNIAkAAIAAAMIgXAAIAAAUIASAAIAAAKIgSAAIAAAXIAZAAIAAAMgAjKAnIAAhNIANAAIAABBIAWAAIAAAMgAhHgIIAAgeIALAAIAAAeg");
	this.shape.setTransform(77.1,12);

	// bg
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#83FF60").s().p("AryBzIAAjlIXlAAIAADlg");
	this.shape_1.setTransform(75.5,11.5);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,151,23);


(lib.block_8_mc = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#84FD63").s().p("AryFEIAAqIIXlAAIAAKIg");
	this.shape.setTransform(75.5,32.5);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,151,65);


(lib.block_8_initials_now_mc = function() {
	this.initialize();

	// 4 secs
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#84FD63").s().p("AAGASIgDgDIgCgDIgBgDIAAgRIABgEIACgCIADgCIAEgBIAEABIADACIABADIABAEIAAADIgGAAIAAgDIgBgEIgCgBIgDABIgBAEIAAAQIABADIADAAIACAAIABgDIAAgFIAGAAIAAAFIgBADIgBADIgDADIgEAAIgEAAgAgMASIAAgdIgGAAIAAgFIASAAIAAAFIgFAAIAAAdg");
	this.shape.setTransform(14.9,5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AARASIAAgTIAAgCIgCAAIgCAAIgBACIAAATIgGAAIAAgTIAAgCIgCAAIgCAAIgBACIAAATIgEAAIAAgZIADAAIAAADIACgCIABgBIADgBIAEABIABADIACgCIACgBIABgBIACAAQAAAAABAAQABAAAAABQABAAAAAAQAAAAABABIABAEIAAAUgAgRASIAAgbIgFAAIAAgDIAEgCIAEgDIADAAIAAAjg");
	this.shape_1.setTransform(26.5,5);

	// 4 secs bubble
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("rgba(32,32,32,0.498)").s().p("AieCCIg8AAIAAldIG1AAIAAFdIkHAAIhyBag");
	this.shape_2.setTransform(15.2,5.8,0.251,0.25);

	this.addChild(this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(9.8,0.3,19.1,11);


(lib.block_8_content_mc = function() {
	this.initialize();

	// LET'S PLAY
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AhZBUQgIgDgGgHQgFgHgDgIQgEgJgBgKIAdgDQABANAFAGQAFAHAHAAQAIAAAEgFQAFgEAAgHQAAgJgFgHQgEgGgGgGIgPgNIgPgMQgGgHgFgKQgFgJABgMQAAgLACgIQAEgIAFgFQAMgMAXABQAJAAAHACQAHADAFAGQAFAGAEAIQADAHABAJIgdAEIgCgKIgDgGIgFgDIgFgBQgHAAgFAEQgDAFAAAIQAAAIAEAGIAMAMIAOANIAPAMQAGAIAFAJQAFAJAAAMQAAALgEAIQgDAIgHAGQgGAFgIADQgKADgKABQgKgBgIgEgAFjBWIAAhIIgkhjIAdAAIAWBCIAAAAIAUhCIAeAAIgkBjIAABIgAEwBWIgFgnIghAAIgFAnIgdAAIAhirIAkAAIAgCrgAEnAVIgMhHIAAAAIgMBHIAYAAgACYBWIAAirIAeAAIAACRIAvAAIAAAagAAoBWIAAirIAqAAQAOgBAKADQALAEAGAFQANAMAAAcQAAAOgEAJQgDAKgGAEQgHAGgKADQgKADgOAAIgNAAIAABHgABFgHIALAAIANgBQAFgCADgDQADgDABgGIABgMIgBgNQgBgFgDgDQgDgDgFgBQgFgCgIAAIgLAAgAjcBWIAAiRIgdAAIAAgaIBXAAIAAAaIgdAAIAACRgAlOBWIAAirIBPAAIAAAaIgyAAIAAAsIAnAAIAAAYIgnAAIAAAzIA2AAIAAAagAmjBWIAAirIAeAAIAACRIAuAAIAAAagAiZgUIAAhBIAXAAIAABBg");
	this.shape.setTransform(45.4,16.4);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(3.4,7.5,84.1,17.8);


(lib.block_7_mc = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#84FD63").s().p("AryH4IAAvwIXlAAIAAPwg");
	this.shape.setTransform(75.5,50.5);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,151,101);


(lib.block_7_initials_now_mc = function() {
	this.initialize();

	// 4 secs
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#84FD63").s().p("AgOASIAAgGIACAAIACAAIAAgDIAAgaIAHAAIAAAbIAAADIgCADIgDABIgEABgAADARIAAgcIgEAAIAAgGIAQAAIAAAGIgGAAIAAAcg");
	this.shape.setTransform(15.1,5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AARASIAAgTIAAgCIgCAAIgCAAIgBACIAAATIgGAAIAAgTIAAgCIgCAAIgCAAIgBACIAAATIgEAAIAAgZIADAAIAAADIACgCIABgBIADgBIAEABIABADIACgCIACgBIABgBIACAAQAAAAABAAQABAAAAABQABAAAAAAQAAAAABABIABAEIAAAUgAgRASIAAgbIgFAAIAAgDIAEgCIAEgDIADAAIAAAjg");
	this.shape_1.setTransform(26.5,5);

	// 4 secs bubble
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("rgba(32,32,32,0.498)").s().p("AieCCIg8AAIAAldIG1AAIAAFdIkHAAIhyBag");
	this.shape_2.setTransform(15.2,5.8,0.251,0.25);

	this.addChild(this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(9.8,0.3,19.1,11);


(lib.block_7_content_mc = function() {
	this.initialize();

	// RONALDO FIELD NOW
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgOBXQgDgBgCgCQgCgCgBgEIgBgGIAAghIABgGQABgEACgCQACgCADgBQADgCAFAAQAEAAACACQADABACACQACACABAEIABAGIAAAhIgBAGQgBAEgCACQgCACgDABQgCACgEAAQgFAAgDgCgAgLAhQgBADAAADIAAAhQAAAEABACQAAAAABAAQAAAAABABQAAAAABAAQABAAABAAQABAAAAAAQABAAABAAQAAgBABAAQAAAAAAAAQACgCAAgEIAAghQAAgDgCgDQAAAAAAAAQgBAAAAgBQgBAAgBAAQAAAAgBAAQgBAAgBAAQgBAAAAAAQgBABAAAAQgBAAAAAAgAAwBYIgIgrIgIArIgJAAIgMhBIAKAAIAHApIAHgpIAKAAIAHApIAHgpIAKAAIgLBBgAgoBYIgPgoIAAAoIgKAAIAAhBIAKAAIAOAlIAAglIAKAAIAABBgAAXgBQgFgBgCgEQgDgDgCgDQgBgEAAgFIAAgsIABgJQACgFADgDQACgCAFgCQAEgCAGAAQAGAAAEACQAEACADACQADADABAFIACAJIAAAsQAAAFgCAEQgBADgDADQgDAEgEABQgEABgGAAQgGAAgEgBgAAbhJQgCADAAAFIAAAsQAAAFACACQABACAFAAQAEAAACgCQACgCAAgFIAAgsQAAgFgCgDQgCgCgEAAQgFAAgBACgAjugBQgEgBgDgEQgDgDgBgDQgCgEAAgFIAAgsIACgJQABgFADgDQADgCAEgCQAEgCAGAAQAGAAAEACQAFACACACQADADACAFIABAJIAAAsQAAAFgBAEQgCADgDADQgCAEgFABQgEABgGAAQgGAAgEgBgAjqhJQgCADAAAFIAAAsQAAAFACACQACACAEAAQAFAAABgCQACgCAAgFIAAgsQAAgFgCgDQgBgCgFAAQgEAAgCACgAEGAAIAAhXIAXAAQAFAAAFACQAEABADADQAGAHAAANIAAAjQAAAOgGAFQgDAEgEACQgFABgFAAgAEVgMIAFAAQAGAAADgDQACgCAAgIIAAgmQAAgGgCgDQgDgDgGABIgFAAgADbAAIAAhXIAPAAIAABKIAXAAIAAANgACpAAIAAhXIAoAAIAAAOIgZAAIAAAVIAUAAIAAAOIgUAAIAAAZIAbAAIAAANgACOAAIAAhXIAOAAIAABXgABZAAIAAhXIAqAAIAAAOIgbAAIAAAVIAUAAIAAAOIgUAAIAAAmgAgtAAIAAhXIAXAAQAFAAAFACQAEABADADQAFAHAAANIAAAjQAAAOgFAFQgDAEgEACQgFABgFAAgAgegMIAFAAQAGAAADgDQACgCAAgIIAAgmQAAgGgCgDQgDgDgGABIgFAAgAhYAAIAAhXIAPAAIAABKIAXAAIAAANgAhrAAIgDgTIgQAAIgDATIgOAAIAQhXIASAAIAQBXgAhwggIgGgmIAAAAIgGAmIAMAAgAihAAIgTg2IgBAAIAAA2IgNAAIAAhXIAOAAIASAyIAAAAIAAgyIAOAAIAABXgAkSAAIgKgkIgEAAIgEAAIAAAkIgPAAIAAhXIAVAAQAGAAAFACQAEABAEADQAGAGAAAOIgBAJIgCAGIgEAEIgDADIAMAngAkkgwIAFAAIAFAAIAEgDIACgDIAAgHQAAgIgCgDIgEgBIgFgBIgFAAg");
	this.shape.setTransform(53.8,14.2);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(23,5.2,61.8,17.9);


(lib.block_6_mc = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#7EF65B").s().p("AryUsMAAAgpYIXlAAMAAAApYg");
	this.shape.setTransform(75.5,132.5);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,151,265);


(lib.block_6_content_mc = function() {
	this.initialize();

	// txt
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgiEwQgHgDgFgFQgFgFgDgHQgCgIAAgHIAAhPQAAgIACgHQADgHAFgFQAFgFAHgDQAIgDAKAAQALAAAFADQAHADAFAFQAFAFADAHQACAHAAAIIAABPQAAAHgCAIQgDAHgFAFQgFAFgHADQgFADgLAAQgKAAgIgDgAgbCyQgDAEAAAJIAABNQAAAIADAFQADAEAIAAQAIAAADgEQADgFAAgIIAAhNQAAgJgDgEQgDgEgIAAQgIAAgDAEgAB3ExIgUhkIgSBkIgVAAIgdiXIAZAAIAPBgIARhgIAWAAIASBgIAPhgIAYAAIgaCXgAhlExIghheIAAAAIAABeIgXAAIAAiXIAXAAIAhBWIAAAAIAAhWIAYAAIAACXgAh6BpQgBAAAAAAQgBAAAAAAQAAAAAAgBQgBAAAAAAIgBgEIABgDQAAgBABAAQAAAAAAAAQAAgBABAAQAAAAABAAIDxAAIACACIABADIgBAEIgCABgABeBTIAAgzIAXAAIAAAIIgOAAIAAANIAKAAIAAAHIgKAAIAAAPIAPAAIAAAIgABOBTIAAgoIgIAoIgEAAIgIgoIAAAoIgIAAIAAgzIALAAIAHAeIAGgeIAMAAIAAAzgAAgBTIAAgzIAJAAIAAAzgAAJBTIAAgrIgIAAIAAgIIAZAAIAAAIIgIAAIAAArgAgfBTIAAgrIgIAAIAAgIIAZAAIAAAIIgIAAIAAArgAg3BTIAAgzIAJAAIAAAzgAhbBTIAAgzIANAAIAGABIAFADQADAEAAAHIAAAVQAAAHgDAEIgFADIgGABgAhSBMIADAAQABAAABAAQAAAAABgBQAAAAABAAQAAAAABgBQABgBAAgEIAAgXQAAgEgBgBQgBgBAAAAQgBAAAAAAQgBgBAAAAQgBAAgBAAIgDAAgAh6BTIAAgzIAXAAIAAAIIgOAAIAAANIALAAIAAAHIgLAAIAAAPIAPAAIAAAIgAApgiQgIgDgFgFQgFgFgCgHQgDgIAAgHIAAhPQAAgIADgHQACgHAFgFQAFgFAIgDQAHgDAKAAQAKAAAIADQAHADAFAFQAFAFADAHQACAHAAAIIAABPQAAAHgCAIQgDAHgFAFQgFAFgHADQgIADgKAAQgKAAgHgDgAAvigQgDAEAAAJIAABNQAAAIADAFQADAEAIAAQAIAAADgEQADgFAAgIIAAhNQAAgJgDgEQgDgEgIAAQgIAAgDAEgAmugiQgHgDgFgFQgFgFgDgHQgCgIAAgHIAAhPQAAgIACgHQADgHAFgFQAFgFAHgDQAIgDAKAAQALAAAGADQAIADAFAFQAFAFADAHQACAHAAAIIAABPQAAAHgCAIQgDAHgFAFQgFAFgIADQgGADgLAAQgKAAgIgDgAmnigQgDAEAAAJIAABNQAAAIADAFQADAEAIAAQAIAAADgEQADgFAAgIIAAhNQAAgJgDgEQgDgEgIAAQgIAAgDAEgAHaghIAAiXIAnAAQAKAAAIACQAIADAFAGQAKALAAAXIAAA9QAAAXgKALQgFAGgIACQgIADgKAAgAH1g2IAIAAQALAAAEgFQAEgEAAgMIAAhDQAAgMgEgEQgEgFgLAAIgIAAgAGLghIAAiXIAaAAIAACBIAqAAIAAAWgAEzghIAAiXIBGAAIAAAWIgsAAIAAAnIAiAAIAAAXIgiAAIAAAtIAvAAIAAAWgAEAghIAAiXIAaAAIAACXgACighIAAiXIBJAAIAAAWIgvAAIAAAnIAjAAIAAAXIgjAAIAABDgAhSghIAAiXIAnAAQAKAAAIACQAIADAFAGQAKALABAXIAAA9QgBAXgKALQgFAGgIACQgIADgKAAgAg4g2IAKAAQAKAAAEgFQAEgEAAgMIAAhDQAAgMgEgEQgEgFgKAAIgKAAgAihghIAAiXIAaAAIAACBIAqAAIAAAWgAjEghIgEghIgdAAIgFAhIgZAAIAciXIAgAAIAcCXgAjNhZIgKhBIAAAAIgLBBIAVAAgAklghIghheIgBAAIAABeIgYAAIAAiXIAZAAIAfBWIABAAIAAhWIAXAAIAACXgAnwghIgSg/IgGABIgHAAIAAA+IgaAAIAAiXIAkAAQALAAAJACQAHADAGAFQALAKAAAYQAAAKgCAGQgBAHgCAEQgDAFgEACIgGAFIAWBEgAoPh0IAJAAIAJgBQADgBADgDQACgDABgEIABgMQAAgNgEgFQgDgDgDgBIgJgBIgJAAgAi1jpQgBAAAAAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAgBgBAAQAAAAAAgBQAAAAAAgBQgBAAAAgBQAAAAABgBQAAAAAAgBQAAAAAAAAQABgBAAAAQAAgBABAAQAAAAABAAQAAgBABAAQAAAAABAAIFrAAQAAAAAAAAQABAAAAABQABAAAAAAQABAAAAABQAAAAABABQAAAAAAAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABAAAAQgBAAAAABQAAAAgBAAQAAABgBAAQAAAAgBAAQAAAAAAAAgAB+kAIgEgCIgCgEIgBgFIAAgbIABgFIACgEIAEgCIAGgBIAGABIAEACIACAEIACAFIAAAbIgCAFIgCAEIgEACIgGABIgGgBgACBkqIgBAFIAAAZIABAFIADABIADgBIACgFIAAgZIgCgFIgDgBIgDABgAAOkAIgFgCIgCgEIgBgFIAAgbIABgFIACgEIAFgCIAGgBIAFABIAEADQACACABACIAAAFIAAAEIgIAAIAAgEQAAgBgBAAQAAgBAAgBQAAAAAAgBQAAAAAAAAIgDgCIgEABIgBAFIAAAZIABAFIAEABIADgBIABgEIAAgGIAIAAIAAAGIAAAFIgDAEIgEACIgFABIgGgBgAgTkAIgEgCIgDgEIgBgFIAAgbIABgFIADgEIAEgCIAGgBIAFABIAFACIACAEIABAFIAAAbIgBAFIgCAEIgFACIgFABIgGgBgAgRkqIgBAFIAAAZIABAFIAEABIADgBIABgFIAAgZIgBgFIgDgBIgEABgACtj/IgMggIAAAgIgIAAIAAgzIAIAAIAMAdIAAgdIAHAAIAAAzgABlj/IAAgzIAIAAIAAAzgABNj/IAAgrIgIAAIAAgIIAaAAIAAAIIgJAAIAAArgAA7j/IgBgLIgKAAIgCALIgIAAIAJgzIALAAIAJAzgAA4kSIgEgWIgDAWIAHAAgAg2j/IAAgzIAIAAIAAArIAOAAIAAAIgAhbj/IAAgrIgJAAIAAgIIAaAAIAAAIIgJAAIAAArgAhzj/IAAgzIAJAAIAAAzgAiXj/IAAgzIANAAIAGABIAEADQAEAEAAAHIAAAVQAAAHgEAEIgEADIgGABgAiOkGIADAAQABAAABAAQAAAAABgBQAAAAABAAQAAAAAAgBQACgBAAgEIAAgXQAAgEgCgBQAAgBAAAAQgBAAAAAAQgBgBAAAAQgBAAgBAAIgDAAgAi2j/IAAgzIAYAAIAAAIIgPAAIAAANIALAAIAAAHIgLAAIAAAPIAQAAIAAAIg");
	this.shape.setTransform(58.8,34.4);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(3.3,3.7,111,61.6);


(lib.block_5_mc = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#43CAEF").s().p("AryH4IAAvwIXlAAIAAPwg");
	this.shape.setTransform(75.5,50.5);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,151,101);


(lib.block_5_content_mc = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0E0E0E").s().p("AgfDjQg1gNgGgxIgGgPIgDgRQgEgNgHgUIgLAAQgMgEgJgJQgKgKgFgMIgFgPIgCgGQgCgLABgKQADgLAGgFQgGgJgEgdIgCgJIAAgEIgBgSQABgbAHgVIAFgPQAIgRAKgPIALgIIADgDIABAAIACgCIAAgBIAAgCIABAAIAAgBIAGgKQAXgVAcgMIAFgBIAIgCIABAAIAKgBIAEAAIAKgEIAMgEIAOgBQANAAANADIALACIABAAIABAAQAIADAFADQAFAEAFABQAJAAADACIACABQAVAKASAQIAAABIABABIACADIAHAHIAAAGIAHAFIAGAEIACACQAdApAAA3QAAAlgLAZIgBAFQAGAFACALQADAKgDALIgCAGIgFAPQgLAVgQAIIgDAEQgDADgDAAIgLgDIgBAFIgIAcIgHAcIgHASQgFARgMASQgCADgEABIgGADQgeAMgdAAQgPAAgRgEgAhPCKQACARADAMQADAPAFAJQAHAMAKAGQAJAGAKABIACAAIAPACQAdACAUgGIAEAAQATAAALgVQAKgPgBgYQABgMACgFIACgEIABgCQgDAHAAARIABgDIAAgBIAFgIIAFgVIAFgVIAFgGIgGgBQgGAAgGABQgLAEgEANIgGASIgEAPQgDAGgDAFIgBAEIgCAEIgCgBIgBgEIAAgCIgJABIgBAIIgBACIgDABIgBgBIAAgJIgGABIAAAAIAAAIIgCACIgFAAIgBgBIgBgEIABgFIgGABIAAAHIAAABIgBABIgFAAIgCgBIABgIIgGAAIAAAIIgDACIgEAAIgBgKIgHAAIgBAKIgBAAIgFAAIAAAAIgBgBIgBgKIgEgBIAAACIgBAGIgBAAIgCABIgBgBIgBAAIgBgFIAAgFIgIgCIAAAEIgBADIgBAAIgCgDIgCgDIAAgCIAAgCQgFgGgDgJIgHgZQgEgMgLgDIAAgBIgBAAIgIgBIgBgBIgKABIgBAAIgBABIAGAJIABAAIABAIIADAMIACALQAAAEADAGIAGAJIgBgMQAAgGgCgEIADAFgAgDCLIACADIAAADIABAKIAGAAIAAgBIABgNIACgBIABAAIACACIABAMIAGAAIABgNIABgBIADAAIABAAIACANIAHAAIAAgNIACgBIACAJIAAAEIAKgCIABgJIAAgCIABAAIABAAIACAGIAAACIADgJIABgEIABgKQACgKAFgFQAAAAAAAAQgBAAAAAAQgBAAgBAAQAAAAgBAAIACgCQACgDAFgCQAIgEADgDQgCgDgIABIgBAAQgHACgIADIgGAEQAJgMAXgBQANgBAOACIABAAIAEgDIABAAIgBAAIABgBIABgHIACgHIAAgBQABgEACgEIAEgCQgCADgBAFIAAAFIABAFQABAEgCADQAagRAGgcQACgIgCgHQgCgHgDgCQgFgDACgMQAFgKACgMQAFgTAAgUIgCgYIgCgDIgBgHIACACQgHgfgSgaIABAEIAAgBIgGgJIgBgCIgGgHIgHgGIABAAIgBgBQgNgNgPgJQgPgJgRgGIgGgCIgBAAQgVgGgVAAQgNAAgPADIgBABIgJACIABgBIgBAAIAAABIgCAAIAAAAIgNAEQgTAHgRAMIgFAEIgPANIgKAMIgDADQgVAcgIAiIACgCIgCAHIgBACQgCAPAAALQAAATAEATQADANAFALQACALgFADQgDACgCAHQgCAHACAIQADAKAFAMIADAGIAEAFIAKAIQAGAFADAEIACABQgHgKACgMIADAAIABACIAAABQAAgIgCgEIACADQAEADgBAFIAAADIABADIACAFQAAABABAAQAAABABAAQAAABABAAQAAAAAAAAIAQgBIgFABIgGABQAAAAAAABQAAAAAAAAQAAAAAAAAQAAABABAAIACABQASgCAJABQAUACAHALQgIgGgLgDIgCAAQgFAAgCABIgCABIACACIAJAFQAHAEACADIgEAAIgBAAQAFAFACAKIABAOIAEAGIABgEIABAAIAAAFIAAAEIAKACIACgKIABAAIABALIAGABIADgLIABgBIACgBIAAABIABABIABAMIAIABIACgOIABgCgAAPBvQgFgFgJACQgKACgDAAQgEgBgBgCQgGgLAHgNQADgJAMgMIABAFQAAAAAAABQABAAAAAAQABAAAAAAQABAAAAgBIABgCIABgBQALADADANIAEAXIAAAGQAAABgBAAQAAABgBAAQAAABgBAAQAAAAgBAAIgEgBgAhPBIQgGAAgGgDQgKABgJgIQgHgGgFgLIAHAGIAHAGQgGgJABgLIABgPQACgKAEgJIADgDQAFgEAIgBIgLgMIAIAFIAGABIARAFIAHACQAYAEAKAAIABAAIAKAAIgCABQAIADgBARIAAAKQABAJgCAJQgFAQgJAFIACgHIACgHQgUANgWADIgJABIgEgBgABKBHQgMgCgQgGIgNgHIADAHIABAHQgMgKgBgLQgDgIAAgKIAAgKQAAgOAGgFIAAAAIAKgBIAEgBIAPAAIACgBIAHAAIANgFIATgGIAAgBIAGgCIAAAAIACgBIADgBQgEAHgGAEIABABQAJABAEAEIADADQAFAJABAKQAEAQgFANIAGgGQgEALgKAHQgEAEgGAAQgJAEgMAAIgHAAgAAvAfQgFAGADAEQAEAFAMgFIAtgQIgtAKQgGABgCgBQgDgCABgDIABgEIgFAFg");
	this.shape.setTransform(17,23.1);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,34,46.3);


(lib.block_4_mc = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#555555").s().p("AryH4IAAvwIXlAAIAAPwg");
	this.shape.setTransform(75.5,50.5);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,151,101);


(lib.block_4_initials_now_mc = function() {
	this.initialize();

	// 4 secs
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AARASIAAgTIAAgCIgCAAIgCAAIgBACIAAATIgGAAIAAgTIAAgCIgCAAIgCAAIgBACIAAATIgEAAIAAgZIADAAIAAADIACgCIABgBIADgBIAEABIABADIACgCIACgBIABgBIACAAQAAAAABAAQABAAAAABQABAAAAAAQAAAAABABIABAEIAAAUgAgRASIAAgbIgFAAIAAgDIAEgCIAEgDIADAAIAAAjg");
	this.shape.setTransform(26.5,5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#555555").s().p("AAEASIAAgGIABAAIADAAIABgCIAAgaIAGAAIAAAbIgBACIgBADIgDACIgEAAgAgIASIgEgDIgCgDIAAgDIAAgRIAAgEIACgCIAEgCIADgBIAFABIABACIABADIAAAEIAAADIgEAAIAAgDIgBgEIgCgBIgCABIgBAEIAAAQIABADIACAAIADAAIAAgDIAAgFIAEAAIAAAFIAAADIgBADIgBADIgFAAIgDAAg");
	this.shape_1.setTransform(15.1,5);

	// 4 secs bubble
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#A5A5A5").s().p("AieCCIg8AAIAAldIG1AAIAAFdIkHAAIhyBag");
	this.shape_2.setTransform(15.2,5.8,0.251,0.25);

	this.addChild(this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(9.8,0.3,19.1,11);


(lib.block_4_content_mc = function() {
	this.initialize();

	// Taught him everything      he knows.
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ABNCPQgFgCgDgDQgEgCgCgFIgCgJIAOgEQABAFADAEQABAEAHgBQADAAABgBQADgCAAgDQAAgEgDgCIgFgHIgPgLIgHgIQgCgEAAgGQABgEABgFQACgDADgDQADgDAEgBQAEgCAFAAQAFAAAEACQAEABADADQAGAGACAJIgOACQgBgEgCgDQgCgCgEgBQgEAAgCACQAAABAAAAQgBABAAAAQAAABAAABQAAAAAAABQAAADABADIAVARIAGAIQACAFAAAGQABAFgCAEQgCAFgDACQgDADgEABQgEABgGABQgFgBgEgBgAhFCPQgEgDgEgEQgDgEgBgFQgBgGAAgGIAAgYQAAgHABgFQABgGADgEQAEgEAEgCQAGgCAHAAQAHAAAFACQAFACADAEQADAEABAGQACAFAAAHIAAAYQAAAGgCAGQgBAFgDAEQgDAEgFADQgFACgHAAQgHAAgGgCgAg/BNQgCAEAAAHIAAAeQAAAGACAEQADACAEAAQAEAAACgCQADgEAAgGIAAgeQAAgHgDgEQgCgDgEAAQgEAAgDADgAkpCPQgGgDgCgEQgDgEgCgFQgBgGgBgGIAAgYQABgHABgFQACgGADgEQACgEAGgCQAEgCAIAAQAHAAAFACQAFACADAEQADAEACAGQABAFAAAHIAAAPIgkAAIAAAMQABAGACAEQACACAFAAQAFAAACgCQACgEAAgGIAAgCIARAAQAAAGgBAGQgCAEgEAEQgCAFgGACQgEACgHAAQgIAAgEgCgAkkBNQgCAEgBAHIAAAEIATAAIAAgEQAAgHgCgEQgCgDgFAAQgFAAgCADgAB6CPIAAgRIASAAIAAARgAAZCPIgKgzIgLAzIgMAAIgPhQIAQAAIAHAxIAAAAIAJgxIANAAIAJAxIAKgxIAPAAIgSBQgAhyCPIAAg+QAAgBAAgBQAAgBAAAAQAAgBAAAAQgBgBAAAAQAAAAgBgBQAAAAgBAAQAAAAgBAAQgBgBAAAAIgGACIgFAEIAAA/IgRAAIAAhQIAQAAIAAAIIAJgHIAFgCIAHgBIAFABIAFADQADAFAAAHIAABCgAiuCPIgOgoIgIAMIAAAcIgRAAIAAhsIARAAIAAA4IATgcIASAAIgSAZIAUA3gAlWCPIAAg+QAAgBgBgBQAAgBAAAAQAAgBAAAAQgBgBAAAAQAAAAgBgBQAAAAgBAAQAAAAgBAAQgBgBgBAAIgEACIgGAEIAAA/IgRAAIAAhsIARAAIAAAjIAEgEIAFgDIAEgBIAGgBIAHABIAEADQAEAFAAAHIAABCgAIWgLQgFAAgEgCQgGgDAAgHQgBgEAEgEQAEgDAEgBIAAAAQgEgBgCgDQgCgCAAgEIABgFIACgDIAEgDIADgDIgFgEIgEgFIgBgIIgBgLQABgJABgGQABgFAEgEQACgDAGgBQAEgCAIAAQAFAAAEACQAFACAEAFIADgFIADgCIADgBIAFgBIAAANIgDAAIgEABIgEACIABAHIABAGQAAAJgCAHQgBAFgDAFQgDADgFABQgFACgGAAIgGAAIgCACIgBACQAAABAAAAQAAABAAAAQABABAAAAQABAAABAAIASACIAKACQAGABACAEQAEAFAAAGQAAAKgJAFQgFACgGABIgOACIgMgCgAIcggQgDABAAAEQAAACADACQACACAIgBQAJABADgCQADgCAAgCQAAgEgDgBQgDgCgJABQgIgBgCACgAIehnIgCADIgCAFIAAARIACAFIACADIAEABIAEgBIACgDIACgFIAAgRIgCgFIgCgDIgEgBgAELgJIAAgPIAEAAQAGABADgDQACgEAAgGIAAgGIgThJIARAAIALAzIALgzIAQAAIgVBWQgBAGgCADQgCAEgDACQgDACgEABIgIACgAl5gLQgFAAgEgCQgHgDAAgHQAAgEAEgEQADgDAEgBIAAAAQgDgBgCgDQgCgCAAgEIABgFIACgDIADgDIAEgDIgGgEIgDgFIgBgIIgBgLQAAgJACgGQABgFADgEQADgDAFgBQAFgCAHAAQAFAAAFACQAEACAEAFIAEgFIACgCIAEgBIAEgBIAAANIgCAAIgFABIgDACIABAHIAAAGQAAAJgBAHQgCAFgDAFQgDADgFABQgEACgHAAIgFAAIgDACIgBACQAAABAAAAQAAABABAAQAAABABAAQABAAABAAIASACIAKACQAFABADAEQADAFAAAGQABAKgKAFQgEACgGABIgPACIgLgCgAl0ggQgDABAAAEQAAACADACQADACAIgBQAJABACgCQADgCAAgCQAAgEgDgBQgCgCgJABQgIgBgDACgAlxhnIgDADIgCAFIAAARIACAFIADADIADABIAFgBIACgDIABgFIAAgRIgBgFIgCgDIgFgBgAFUgiQgDgBgDgDQgFgEAAgJIAAgzIgJAAIAAgNIAJAAIAAgXIAQAAIAAAXIAMAAIAAANIgMAAIAAAuQAAAEACABQAAABABAAQAAAAABABQAAAAABAAQABAAAAAAIAGAAIAAAPIgIABIgJgBgACqgjQgFgDgDgEQgDgEgBgFQgCgGAAgGIAAgYQAAgHACgFQABgGADgEQADgEAFgCQAFgCAHAAQAHAAAGACQAEACAEAEQACAEACAGQACAFgBAHIAAAPIgjAAIAAAMQAAAGADADQACADAEAAQAFAAACgDQACgDAAgGIAAgCIARAAQABAGgCAFQgCAFgDAEQgDAFgFACQgEACgIAAQgHAAgFgCgACwhlQgDAEAAAHIAAAEIASAAIAAgEQAAgHgCgEQgCgDgFAAQgEAAgCADgAAxgjQgFgDgDgEQgDgEgCgFQgBgGAAgGIAAgYQAAgHABgFQACgGADgEQADgEAFgCQAFgCAIAAQAGAAAFACQAGACACAEQADAEACAGQABAFABAHIAAAPIgkAAIAAAMQAAAGACADQADADAFAAQAEAAACgDQACgDABgGIAAgCIARAAQgBAGgBAFQgBAFgEAEQgDAFgFACQgFACgGAAQgIAAgFgCgAA2hlQgCAEAAAHIAAAEIATAAIAAgEQgBgHgCgEQgCgDgEAAQgFAAgDADgAj0giQgEgBgDgDQgEgEgBgJIAAgzIgJAAIAAgNIAJAAIAAgXIARAAIAAAXIAMAAIAAANIgMAAIAAAuQAAAEABABQABABAAAAQABAAAAABQABAAABAAQAAAAABAAIAGAAIAAAPIgJABIgIgBgAnAgmIgDgFIgBgIIAAhAIARAAIAAA+QAAABAAAAQAAABAAABQABAAAAABQAAAAABAAIAEABIAFgBIAFgDIAAg/IARAAIAABQIgQAAIAAgIIgEAEIgFADIgEACIgHABQgHgBgDgEgAoDgnQgEgFgBgHQABgHACgFQACgGAEgEQAFgFAGgDQAHgEAJgDIAAgFQAAgFgBgDQgCgCgFgBQgGAAgCADQgBADgBAGIgQAAQAAgMAIgHQADgDAFgBQAFgCAGAAIAKABIAIAEQAGAFAAALIAAA1IABAIIgQAAIgBgHIgJAHQgEACgHAAQgIAAgEgGgAnthGIgGAFIgDAFIgBAGQAAAEACABQACABAEAAQAEAAADgCIAEgFIAAgVgAHvgjIAAg+QAAgBAAgBQAAgBAAAAQgBgBAAAAQAAgBAAAAQgBAAAAgBQgBAAAAAAQgBAAgBAAQAAgBgBAAIgFACIgGAEIAAA/IgRAAIAAhQIAQAAIAAAIIAJgHIAGgCIAGgBIAGABIAFADQADAFAAAHIAABCgAGvgjIAAhQIAQAAIAABQgAGPgjIAAg+QAAgBAAgBQAAgBAAAAQgBgBAAAAQAAgBgBAAQAAAAAAgBQgBAAAAAAQgBAAgBAAQAAgBgBAAIgFACIgFAEIAAA/IgRAAIAAhsIARAAIAAAjIADgEIAFgDIAEgBIAHgBIAGABIAFADQADAFAAAHIAABCgADegjIAAhQIAPAAIAAAJIABAAQADgGAFgCQAFgDAGAAIADAAIAAASIgEgCIgGgBQgFAAgDAEQgDACAAAGIAAA3gABygjIgUhQIARAAIALA2IALg2IARAAIgUBQgAgZgjIAAg+QAAgBAAgBQAAgBAAAAQAAgBgBAAQAAgBAAAAQgBAAAAgBQgBAAAAAAQgBAAAAAAQgBgBgBAAIgFACIgFAEIAAA/IgRAAIAAg+QAAgBAAgBQAAgBAAAAQgBgBAAAAQAAgBgBAAQAAAAgBgBQAAAAgBAAQAAAAgBAAQAAgBgBAAIgFACIgFAEIAAA/IgRAAIAAhQIAPAAIAAAIIAJgHIAFgCIAFgBQAGAAAEACIAFAIIAGgGIAEgCIAEgCIAEAAQAIAAAFAEQADAFAAAHIAABCgAh7gjIAAhQIARAAIAABQgAiagjIAAg+QAAgBAAgBQAAgBAAAAQgBgBAAAAQAAgBAAAAQgBAAAAgBQgBAAAAAAQgBAAgBAAQAAgBgBAAIgFACIgFAEIAAA/IgSAAIAAhsIASAAIAAAjIADgEIAFgDIAEgBIAHgBIAGABIAEADQAEAFAAAHIAABCgAkhgjIAAg+QAAgBgBgBQAAgBAAAAQAAgBAAAAQgBgBAAAAQAAAAgBgBQAAAAgBAAQAAAAgBAAQgBgBgBAAIgFACIgFAEIAAA/IgRAAIAAhsIARAAIAAAjIAEgEIAFgDIAEgBIAHgBIAGABIAEADQAEAFAAAHIAABCgAoxgjIAAhcIgSAAIAAgQIA3AAIAAAQIgSAAIAABcgAGviAIAAgPIAQAAIAAAPgAh7iAIAAgPIARAAIAAAPg");
	this.shape.setTransform(60.8,19.2);

	// Layer 2
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAABTIgDgBIgEgCQgGgBgFgEQgEgDgDgFIgCgFIgEgHIgCgEIgBgEIAAgCIAAgCIgDgPIgEgNQgDgCgDgHIgDgGIAAgEQABgEACgBQgCgDgCgJIAAgEIAAgGQAAgIACgGIACgFIAFgKIAEgCIABgBIABgBIAAAAIAAgBIACgDQAHgGAJgEIADgBIABAAIAEAAIADgBIAEgCIADAAIAIABIADABIABAAIAEACIADABIAEABIABAAQAGADAFAFIABACIACABIAAACIABABIACABIACABIAAABQAJAMAAARQAAALgDAIIAAACQABABABAEQABADgBABIgCAGQgCAGgEACIgHAaIAAABIgBAEIAAACIAAAEIgCAEIgEAHIgCAFIgHAIQgGAFgIAAIgBAAIgCACIgBAAIAAAAIgBABIgBAAgAgHBLIAAABIACACQADADACAAIAAgBIABAAIAAAAIABgBIABAAIAAgBIACgCIAEgLIAFgQIgBABQABgDAAgEIgBgCIgHACIgEABIgCAYIAAgLIAAgNIAAAAQgDAAgFgCIAAAAIgBABIAAACIAAADIAAAAgAALBBIAAABIgBADIgDAHIACAAQAFgBAEgEQADgCACgEIABAAIABgDQABgDAAgEIABgEIACgCIgBABIgBACIAAAEIACgEIACgCIAAgCIAAgDIAAgBIABgDIACgKIADgNIgCAAIAAgBIgCABIgCAAIgBACIgCAFIgBAJIgFASIAAgBIAFgVIgFATIgCAEIgBACIAAABIgBABIAAAAIgBACIAAAAIgBABIAAgBQAAAAABAAQAAAAAAgBQAAAAAAAAQAAAAAAAAIAAgDQAAAAAAAAQAAAAAAAAQgBAAAAABQAAAAAAAAIAAACIAAAAIgBAAIgBABIAAADIACgBIAAAAIgBACIgBADIAAAAIAAgDIgDACgAgZAzIAAAEIACAHIACADQAFAIAHACIAAAAIgBgKIgBgCIAAADIgCgDIgBgBIAAgCIACACIAAgBIAAABIACABIAAAAIgBgEIgBABIAAgBIAAgBIgCAAIgBgCQAAAAAAgBQAAAAAAAAQAAAAAAAAQAAAAgBAAIAAABIAAABIgBAAIgBgCIAAgCIgBgEIgFgTIgBAAIAFAWIAAgBIgFgTIgBgLIgBgBIgBgCIgDAAIgCAAIgCgBIAFAYIABADIAAAEIABADIABACIABADIAAgDIAAgBIgBgCIAAgBIACACgAAMA/IACgBIAAgDgAAXAnIgBABIgEANIAFgNIAAgBIABAAIAAAAIADgMgAgQA1IgDgNIgBgBIgEgMIADAMIABAAIAEAOgAgEApQAAABAAAAQABAAAAABQAAAAABAAQAAAAABAAQAAAAABAAQAAAAAAAAQAAAAAAAAQAAAAAAAAIACAAIADAAIABgBIAAgBIADAAIABgBIABgBQAAAAAAAAQAAAAAAAAQABAAAAAAQAAAAABAAIABgBIABAAIABgBIAAgBIAAgCIAAABIACgBIAAgCIgBgBIgBgBIAAABIAAABIAAACIAAgCIgBAAIgBACIAAABQAAAAAAAAQAAgBAAAAQgBAAAAAAQAAAAAAAAIgBAAIgBABIAAAEIgBgDIgBgBIgCABIgBABIAAAEIAAgEIgBgBIgCAAIgBABQAAAAgBAAQAAAAAAABQAAAAgBAAQAAABAAAAIAAACQAAgBAAgBQAAAAAAgBQAAAAAAgBQAAAAAAAAIgBgBIgBABQAAAAgBAAQAAAAAAAAQgBABAAAAQAAABAAAAIAAgBIgBgCIgCgBIAAAAIgCABIAAgBIAAAAIgBgBIgBAAIgBABIABADIgBgDIAAgBIAAgCIgCAAIAAACIAAgCIgBgBIAAgBIgBAAIAAACIAAABIAAABIABABIAAgBIABACIACACIABABIABAAQAAAAAAAAQAAAAABAAQAAAAAAAAQAAAAAAAAIAAgBIAAACIACABIACAAIABAAgAAAAkIADgBIABAAIABAAIAAgCIAAgCIAAgBQAAABAAAAQABABAAAAQAAABAAAAQAAABABABIABgBIABAAQABAAAAgBQAAAAAAgBQAAAAgBAAQAAgBAAAAIABABIABACIABgCIABAAIgBgCIABAAIABACIAAgBIACAAIAAgCIABAAIAAgCQAAgBAAgBQABAAAAgBQAAAAAAgBQABAAAAgBIgBAAIAAAAIACgCIAEgCQAAAAAAAAQgBAAAAAAQAAAAgBAAQAAAAgBAAIgBAAIgEABIgBABQACgEAJAAIABACIgCABIgCABIACgBQAAAAABAAQAAAAAAAAQAAAAAAAAQAAABAAAAIgBAFIAAABQABgEABgCIADgDIACgBIAAAAIgBgBIABAAIACAAIAAgBIABgBIAAgBIAAgBIABgCIABgBIgBACIAAACIABABIAAABIADgDQACgBACgEIADgGIAAgDIgCgDQgCgBABgFIABAAQADgJAAgJIgBgHIAAgBIgBgCIABABQgCgKgFgIIAAABIgCgCIgBgBIgBgCIgBgBIgBgBIgBgBIABABQgIgIgLgEIAAAAIgCAAIAAAAQgGgCgHAAIgIABIAAAAIgDABIAAAAQgMADgJAJIgBAAIgBACIAAAAIAAAAIgCACIABgBQgIAJgCALIABgBIgBACIAAABIgBAIQgBAKAEAIIAAAAQABAFgCABIgBADIAAADIACAGQADAEACABIADADIAAgCIAAgCIAAgCIAAABIABACIAAABIAAABIABACIABAAIAEAAIgCABIAAAAIABABIAAAAQADABABACQACACAAAEQABgCgCgEQAAAAAAgBQAAAAAAAAQABAAAAAAQAAAAAAAAIACABIgDgCIgBgBIABgBQAIAAAEAEIgGgCIgBAAIgCAAIgBAAIABABIADABIACACIgBAAIACAFIAAACIAAAAIABACIACAAIAAABIACgCIAAAAIgBACIABAAIABACIABgCIAAgBIAAADIABAAIACABQABgBAAgBQAAAAAAgBQABAAAAgBQAAAAABgBIgBACIAAADIABAAIABAAIABABIAAgDgAgPA8IgBAAIAAgBIAAgBIAAAAIABABIABgBIgBABIAAABIABAAgAAHAZIAAAAIgEgBIgBgCIAAABIADABIACAAQAAAAAAAAQABAAAAgBQAAAAABAAQAAAAAAgBIgBADIAAACIgBgCgAgGAZIgBgCIABABIADAAIACgBIABgBIAAAAIAAABIgCACIgDAAIgBAAIgBACIABgCgAAFAWIgEgCIgBgBIAAABIgCACQgBAAAAAAQgBAAAAAAQAAAAgBAAQAAAAAAgBIAAgCQABgGACgFIACgDIAAACIAAAAIAAAAIABAAIAAgCIADADQACAFABAGIAAACIgBABIgBAAgAAPAHIgGgDIABABIABADQgCgCgCgEIAAAAIAAgEIAAgDQgBgFACgBIADAAIAGgBIACAAIAEgCIAGgBIABgBIACgBIAAABIABgBIgDADIAAABQABAAAAAAQABAAAAAAQABAAAAABQABAAAAAAIABACIACAFIAAAFIAAACIABgCQAAAEgEACIgDACIgFABQgFAAgGgCgAAPgCQgBAAAAAAQAAABAAAAQAAAAAAABQAAAAAAAAQAAAAABAAQAAAAABAAQAAAAABAAQABAAAAAAIAPgEIgOADIgDAAIAAgCIAAgBIgBACgAgbAIIgCAAIgDgCQgDgCgBgEIABACIACACIgBgEIAAgFIACgFIABgCQAAAAABAAQAAgBABAAQAAAAABAAQAAAAABAAIAAgBIAAAAIgDgDIACABIAAAAIAHACIADABIAKACIABgBIACAAIAAABQACABAAAFIAAADIAAAEIAAAAQgCAEgDACIABgDIABgBIgGADQgFACgEAAIgGgBgAAog4IAAAAIAAACIAAgCg");
	this.shape_1.setTransform(80.1,28.1);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(2.7,4.7,116.1,31.8);


(lib.block_3_mc = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#E2E2E0").s().p("AryKEIAA0IIXlAAIAAUIg");
	this.shape.setTransform(75.5,64.5);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,151,129);


(lib.block_3_initials_now_mc = function() {
	this.initialize();

	// 4 secs
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#E2E2E0").s().p("AgOASIAAgGIACAAIACAAIAAgDIAAgaIAHAAIAAAbIAAADIgCADIgDABIgEABgAADARIAAgcIgEAAIAAgGIAQAAIAAAGIgGAAIAAAcg");
	this.shape.setTransform(15.1,5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AARASIAAgTIAAgCIgCAAIgCAAIgBACIAAATIgGAAIAAgTIAAgCIgCAAIgCAAIgBACIAAATIgEAAIAAgZIADAAIAAADIACgCIABgBIADgBIAEABIABADIACgCIACgBIABgBIACAAQAAAAABAAQABAAAAABQABAAAAAAQAAAAABABIABAEIAAAUgAgRASIAAgbIgFAAIAAgDIAEgCIAEgDIADAAIAAAjg");
	this.shape_1.setTransform(26.5,5);

	// 4 secs bubble
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("rgba(32,32,32,0.498)").s().p("AieCCIg8AAIAAldIG1AAIAAFdIkHAAIhyBag");
	this.shape_2.setTransform(15.2,5.8,0.251,0.25);

	this.addChild(this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(9.8,0.3,19.1,11);


(lib.block_3_content_mc = function() {
	this.initialize();

	// Mercs strike again!
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AhxDKQgHgBgFgDQgJgEAAgJQAAgGAEgFQAEgFAHgBIAAgBQgFgCgDgDQgDgDAAgGIABgGIAEgFIAJgIIgHgFQgDgDgCgFIgCgKIgBgRQAAgMACgHQACgJAEgFQAFgFAHgCQAHgCAJAAQAIABAHACQAGADAFAGIAJgJIAFgCIAGgBIAAAUIgCgBIgCAAIgGABQgDABgCADIACARQAAANgCAJQgCAIgFAGQgEAFgGACQgIADgJAAIgHAAIgDACQAAAAgBAAQAAAAAAABQAAAAAAABQAAAAAAABQgBAEAFABIAaACQAIAAAGACQAHADAFAFQAEAFAAALQAAAOgNAGQgGADgJACQgJABgMAAIgPgBgAhqCrQgEACAAAFQAAAFAEACQAEABAMAAQAMAAAEgBQAEgCAAgFQAAgFgEgCQgEgCgMAAQgMAAgEACgAhmBJIgEAEIgCAHIAAAXIACAIIAEADIAFABIAGgBIADgDQACgDAAgFIAAgXQAAgFgCgCIgDgEIgGgCgAgkCiQgHgHAAgLQAAgJADgIQAEgHAGgGQAGgGAKgFQAJgFALgFIAAgHQAAgHgDgDQgDgFgEAAQgIABgCAEQgDAFAAAHIgYAAQABgRALgKQAFgEAGgDQAHgCAIAAQAHAAAFACQAHACAEAEQAJAIAAAPIAABJIACAMIgXAAIgBgJQgHAFgEADQgGADgIgBQgNABgFgIgAgGB2IgIAIQgCADgBAEIgCAHQAAAGADACQADACAFAAQAFAAADgDIAGgHIAAgegAjWCiQgGgHgBgLQAAgJAEgIQADgHAGgGQAHgGAJgFQAJgFANgFIAAgHQAAgHgDgDQgDgFgGAAQgHABgDAEQgDAFAAAHIgXAAQABgRAKgKQAEgEAHgDQAHgCAIAAQAJAAAFACQAHACAFAEQAIAIABAPIAABJIABAMIgXAAIgBgJQgGAFgHADQgGADgJgBQgMABgFgIgAi4B2IgHAIQgEADgBAEIgBAHQAAAGADACQACACAGAAQAFAAAEgDIAHgHIAAgegAC6CoIAAgaIAYAAIAAAagACKCoIAAhYQAAgFgCgBQgDgCgDgBQgEABgDACIgIAFIAABZIgYAAIAAhyIAXAAIAAAMIAGgGIAGgEIAIgDIAIgBQAFABAEABQADACADADQAFAGAAALIAABcgAAxCoIAAhyIAXAAIAABygAC9B7IgEhrIAbAAIgFBrgAAxAlIAAgVIAXAAIAAAVgAGHg0QgHgDgEgFQgFgGgBgHQgDgIAAgKIAAghQAAgJADgIQABgHAFgGQAEgGAHgCQAHgDAKAAQAKAAAHADQAHACAFAGQAEAGACAHQABAIAAAJIAAAWIgxAAIAAAQQAAAJADAFQAEAFAGAAQAGAAAEgFQADgFAAgJIAAgDIAXAAQAAAJgCAHQgCAIgEAFQgFAGgGACQgHAEgKAAQgKAAgHgEgAGOiOQgDAFAAAJIAAAGIAaAAIAAgGQAAgJgDgFQgEgFgGABQgGgBgEAFgACNgyQgGgCgDgCQgHgHAAgNIAAhGIgOAAIAAgTIAOAAIAAgfIAXAAIAAAfIAQAAIAAATIgQAAIAABBQAAAEACADQACACAEAAIAIAAIAAAVIgMABQgGAAgFgCgAA8gzQgHgCgEgDIgHgKQgDgHgCgHIAWgFQABAGACAGQAEAGAIAAQAEgBADgDQADgCAAgFQAAgEgDgFIgIgHIgVgRQgGgFgCgFQgEgGAAgJQAAgGADgFQACgGAFgEQADgEAHgCQAFgCAGAAQAIAAAFACQAGACAFAEQAIAJADAMIgUAEQgBgHgEgEQgDgEgGABQgEgBgDADQgDADAAAEQAAAEADAEIAeAYQAFAFAEAHQADAGAAAIQgBAHgCAHQgDAFgDAEQgFAEgGABQgGADgIAAQgHAAgGgDgAg7gzQgFgCgFgDIgHgKQgDgHgBgHIAUgFQABAGAEAGQADAGAIAAQAFgBADgDQACgCAAgFQAAgEgDgFIgIgHIgWgRQgEgFgDgFQgEgGAAgJQAAgGACgFQADgGAEgEQAFgEAFgCQAGgCAHAAQAHAAAFACQAGACAEAEQAKAJACAMIgUAEQgBgHgDgEQgEgEgFABQgFgBgDADQgCADAAAEQAAAEACAEIAeAYQAFAFADAHQADAGABAIQAAAHgDAHQgCAFgEAEQgFAEgGABQgHADgGAAQgIAAgHgDgAiRg0QgHgDgFgFQgEgGgCgHQgCgIAAgKIAAghQAAgJACgIQACgHAEgGQAFgGAHgCQAGgDALAAQAJAAAHADQAHADAFAFQAEAFACAHQACAIAAAJIgYAAIAAgDQABgJgDgFQgEgFgGABQgHgBgDAFQgDAFgBAJIAAAqQABAJADAFQADAFAHAAQAGAAAEgFQADgFgBgJIAAgHIAYAAIAAACQAAAKgCAIQgBAHgFAGQgEAFgIADQgHAEgJAAQgLAAgGgEgAktg0QgGgDgFgFQgEgGgCgHQgCgIAAgKIAAghQAAgJACgIQACgHAEgGQAFgGAGgCQAIgDAJAAQALAAAGADQAIACAEAGQAEAGACAHQACAIAAAJIAAAWIgxAAIAAAQQAAAJADAFQAEAFAFAAQAHAAADgFQAEgFAAgJIAAgDIAXAAQAAAJgCAHQgCAIgFAFQgEAGgHACQgGAEgLAAQgJAAgIgEgAkliOQgDAFAAAJIAAAGIAaAAIAAgGQAAgJgEgFQgDgFgHABQgFgBgEAFgAFSgzIgTg4IgBAAIgLARIAAAnIgXAAIAAiXIAXAAIAABOIABAAIAZgnIAaAAIgZAjIAbBNgADygzIAAhwIAXAAIAABwgACwgzIAAhwIAWAAIAAAMQAFgHAGgEQAIgDAIAAIAFAAIAAAYIgGgCIgJgBQgHAAgEAFQgFADAAAIIAABNgAjmgzIAAhwIAXAAIAAAMQAFgHAGgEQAIgDAIAAIAEAAIAAAYIgFgCIgJgBQgGAAgGAFQgEADAAAIIAABNgAlogzIAAh2IAAAAIgYB2IgNAAIgYh2IAAB2IgWAAIAAiXIAiAAIASBYIABAAIAShYIAiAAIAACXgADyi1IAAgVIAXAAIAAAVg");
	this.shape.setTransform(47.7,27.2);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(3.2,6.9,89,40.7);


(lib.block_2_mc = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#43CAEF").s().p("AryJJIAAyRIXlAAIAASRg");
	this.shape.setTransform(75.5,58.5);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,151,117);


(lib.block_2_initials_4secs_mc = function() {
	this.initialize();

	// 4 secs
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#43CAEF").s().p("AAGASIgDgDIgCgDIgBgDIAAgRIABgEIACgCIADgCIAEgBIAEABIADACIABADIABAEIAAADIgGAAIAAgDIgBgEIgCgBIgDABIgBAEIAAAQIABADIADAAIACAAIABgDIAAgFIAGAAIAAAFIgBADIgBADIgDADIgEAAIgEAAgAgMASIAAgdIgGAAIAAgFIASAAIAAAFIgFAAIAAAdg");
	this.shape.setTransform(14.9,5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AARASIAAgTIAAgCIgCAAIgCAAIgBACIAAATIgGAAIAAgTIAAgCIgCAAIgCAAIgBACIAAATIgEAAIAAgZIADAAIAAADIACgCIABgBIADgBIAEABIABADIACgCIACgBIABgBIACAAQAAAAABAAQABAAAAABQABAAAAAAQAAAAABABIABAEIAAAUgAgRASIAAgbIgFAAIAAgDIAEgCIAEgDIADAAIAAAjg");
	this.shape_1.setTransform(26.5,5);

	// 4 secs bubble
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("rgba(32,32,32,0.498)").s().p("AieCCIg8AAIAAldIG1AAIAAFdIkHAAIhyBag");
	this.shape_2.setTransform(15.2,5.8,0.251,0.25);

	this.addChild(this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(9.8,0.3,19.1,11);


(lib.block_2_content_mc = function() {
	this.initialize();

	// What a goal
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("ACSBcQgHgBgFgCQgJgFAAgJQAAgHAEgFQAFgEAGgCIAAAAQgFgCgDgDQgDgDAAgGIABgGIAEgFIAJgHIgHgHQgDgDgCgEIgCgLIgBgOQAAgLACgJQACgHAFgFQAEgGAHgBQAHgCAKAAQAHAAAHACQAGADAGAGIAIgJIAFgCIAGAAIAAATIgCAAIgCAAIgGABQgCAAgDACIADASQAAANgDAHQgCAJgEAEQgFAGgGACQgHACgJAAIgIAAIgDACQAAABAAAAQgBAAAAABQAAAAAAABQAAAAAAABQAAAEAEAAIAaADQAIAAAGADQAHACAFAFQAEAGAAAJQAAAPgMAGQgHADgJABQgJACgLAAIgQgBgACZA+QgEACAAAEQAAAEAEACQAEACAMABQAMgBAEgCQAEgCAAgEQAAgEgEgCQgEgCgMAAQgMAAgEACgACdgjIgDADIgDAHIAAAYIADAGIADADIAFABIAGgBIAEgDQABgDABgDIAAgYQgBgEgBgDIgEgDIgGgBgAE5A1QgGgIAAgLQAAgJADgHQADgIAGgGQAHgEAJgFQAJgFANgFIAAgHQAAgHgDgEQgDgDgGAAQgHgBgDAFQgDAEAAAIIgXAAQABgSAKgIQAFgFAGgCQAHgCAIAAQAJAAAGACQAGABAFAEQAJAHAAAQIAABGIABAMIgWAAIgCgJQgGAGgHADQgGADgIAAQgMgBgGgGgAFYAJIgIAHQgDAEgBADIgCAHQAAAFADADQADADAFAAQAFAAAEgEIAHgHIAAgegADwA4QgHgDgEgFQgFgGgCgHQgCgIAAgJIAAggQAAgJACgIQACgHAFgGQAEgGAHgCQAHgDAKAAQAKAAAHADQAHACAEAGQAFAGACAHQABAIAAAJIAAAgQAAAJgBAIQgCAHgFAGQgEAFgHADQgHAEgKAAQgKAAgHgEgAD3ggQgDAFAAAJIAAAoQAAAJADAFQAEAFAGAAQAGAAAEgFQADgFAAgJIAAgoQAAgJgDgFQgEgFgGABQgGgBgEAFgAABA1QgEgIAAgLQAAgJADgHQABgIAHgGQAGgEAKgFQAJgFANgFIAAgHQAAgHgDgEQgDgDgGAAQgIgBgCAFQgDAEAAAIIgWAAQABgSAIgIQAFgFAHgCQAHgCAIAAQAIAAAGACQAHABAEAEQAJAHAAAQIAABGIACAMIgXAAIgBgJQgHAGgGADQgGADgJAAQgMgBgGgGgAAgAJIgIAHQgDAEgBADIgBAHQAAAFADADQACADAGAAQAFAAAEgEIAHgHIAAgegAhNA6QgFgCgDgCQgIgHAAgNIAAhEIgNAAIAAgTIANAAIAAgfIAYAAIAAAfIAQAAIAAATIgQAAIAAA/QAAAEACADQACACAEAAIAIAAIAAAVIgMABQgHAAgFgCgAi4A1QgGgIAAgLQAAgJADgHQADgIAGgGQAHgEAJgFQAJgFANgFIAAgHQAAgHgDgEQgDgDgGAAQgHgBgDAFQgDAEAAAIIgXAAQABgSAKgIQAFgFAGgCQAHgCAIAAQAJAAAGACQAGABAFAEQAJAHAAAQIAABGIABAMIgWAAIgCgJQgGAGgHADQgGADgIAAQgMgBgGgGgAiZAJIgIAHQgDAEgBADIgCAHQAAAFADADQADADAFAAQAFAAAEgEIAHgHIAAgegAGRA5IAAiVIAXAAIAACVgAjkA5IAAhVQAAgEgDgCQgCgDgEABQgEgBgDADIgIAFIAABWIgXAAIAAiVIAXAAIAAAxIAMgJIAHgCIAIgBQAFAAAEABQADABADADQAFAHAAALIAABZgAlQA5IgThiIgSBiIgVAAIgdiVIAYAAIAQBeIARheIAWAAIASBeIAPheIAYAAIgbCVg");
	this.shape.setTransform(44.5,16.2);

	// Layer 1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#0E0E0E").s().p("ABvBmQgegDgHAAQgBAAgBAAQgBAAAAABQgBAAAAAAQAAAAABABIADABIgOgCIADADIg+gFIAEgCIgNgDQAFAAgFgCQgJgEgugEIAZAAQAVAAgOgDQgNgCAOABIAPAAIAGADIAJAEIAAgBQgWgKgLgOIgEgFIgGgEIgHgCIgGAAIAKgDQAKAAAFAHQABABAAAAQABABAAAAQAAAAABAAQAAAAAAgBQAAAAAAgBQAAAAAAgBQgBAAAAgBQAAgBgBAAQgEgEgGgDQgEgCgBgFIgCgPQgDgMgCgCQgDgGgMADIAGgDQAIgCAFAEIAFAFQAFACADgBIABgBIABgBIABgBIACgEQAAgDgCgBQgCgDgDgBIgBAAIgJgCIgLgCQgEgBgDgDIAHAFIAKADIAFABIAGABIADADQABAAAAAAQAAAAAAAAQABAAAAABQAAABgBAAIAAADQgBgEgKgBIgRgFQgGgDgEgDQgFgGgFgIIgFgHQgDgCgGAAIAGgBQAGABAHAIQADAFAFABIAAAAIACABIABAAIABAAQADAAACgCIAEgEQAAAAAAgBQAAAAABgBQAAAAAAgBQAAgBAAAAQgBgEgEgEIgDgDIgFgCIgHgDIgHgBIgGgCIgDgCIgCgCIgCgBIABABIACACQADADAHACIAHACIAHACIAEACIACADQAEADABAEIgBADQAAgIgOgFIgSgFQgMgDgFgHIgEgGIgFgLQgBgFgFgDQgDgDgEgBIAGABQAJACAGAKQAEAFAFAEQAGAFAFgEQAEgDgDgHQgCgFgEgEQgEgDgFgCIgSgFQgGgBgFgDQgFgFgEgGIAGAEQAHAEAHABIATAEIAKADIAKAFQAGAFADAHQAFAJAEADQAFAFAFgBQAFgBABgFQAAgFgCgDQgCgEgGgDIgPgFQgHgCgDgHIgBgHIACAFQADAFAGABIAJADIACAAIADACIAEABIAEADIAHAGIACADIADAEIABADIABAEIABAAIgBgCIgDgJIgDgEIgGgHIgEgBIAFABQAFACAFAEQAEAFABAIQACAJAFAGQAGAFAHgBQAEAAABgDQACgDgEgEIgNgJQgIgGAAgJIAAACIAEAFQAIAGAQADQAKACASABQAPADAPAKQAWAGAOATQAPASAAAXQAAASgIAQQgJAQgOAKIAAAAIAXAEIAmAFIgPABIADACIgJAAQgCAAgBABQgCAAAAAAQgBAAAAAAQABAAABABQAAAAABAAQAAABAAAAQAAAAAAAAQAAAAgBAAIgEAAIAfAHIgdgDgAAOA6IgOAHIAAABIAAABIAGANIACABQAFADAFACQAOAEAMgCIABgBIAFgFIAAgCIAAgDQgDgFgBgFQAAAAgBgBQAAAAAAgBQgBAAAAgBQgBAAAAAAIgCgBQgMgBgLgEIgCAAIgCAAgAA/BQIgGABIgEADIgBACIAAAAIAKgDIAKgFIgBAAIgIACgABBAvIgNANIgBACQgBAAAAABQAAAAAAABQAAAAAAABQAAABAAAAIABADIACAGIABABIADABIADgBIAMgDIACgBIAEgEIABgBIAFgQIgBgCIgBgBIgLgDIgCAAQAAAAgBAAQAAAAgBABQAAAAgBAAQAAAAgBABgAgNA/QAGAJAHAFIAAgBIgCgHQgCgDgCgCQgFgEgFgGIgEgEIgCgCQADAIAGAHgABjAjIgHALIgCADIgBAEIgHAPIAAABIABgBIAFgFQAJgMADgQIAAgBgAgNAYIgBACIgCAGIgCALIABADIALAMIADADQAAAAABAAQABABAAAAQABAAAAAAQAAAAAAgBIALgGIABgCIgEgWIAAgCQgBAAgBgBQAAAAgBAAQAAgBgBAAQAAAAgBAAIgFgBIgIgDIgBAAIgCABgAAdALIgBABIgNAMIgBABQgBABAAAAQAAABgBABQAAAAAAABQAAAAAAABIAEASIACAFIACABIAIADIAPACQADABACgCIAPgPIABgBIABgCIAAgDIAAgCQABAAAAAAQABAAAAABQAAAAABAAQAAABAAABIACADIACAAIAMADQADABADgDQAEgEAEgGIACgEIABgCIAAgDQAAgIgDgKIgCgDIgIgCIgKgCQgBAAAAAAQAAABgBAAQAAAAgBAAQAAABgBAAIgBAAIgEAGIAAAAIgEAEIgBABIgBADIAAAEQABAFgCABQAAAAAAAAQAAgBAAAAQgBAAAAAAQAAgBAAAAIAAgEIgBgCIgCgBIgDgBIgNgDIgHgCIgCgBQgBAAAAABQgBAAAAAAQgBAAAAABQgBAAAAABgAgUgCQgEAGgCAJQgCAJACAJIABAJIABAEIABgBIABgFIAEgOQACgEAAgEIgBgHIgBgKIAAAAQAAgBAAAAQAAAAAAAAQgBgBAAAAQAAAAAAAAIgBAAgAgrASIAAAGIABAEIABADIAFAFIADADIAAgBIgDgEIgEgEIgBgDIAAgDIgBgGIgBgEIAAAEgAACgUQgGAGgJAKIgBACIABAJIABAKIABACQAIADAIABQAEABADgDIANgMQAEgEgBgFIgCgQIgBgBIgCgBQgIgDgJAAIgEABgAAkgTIgEABQgBAAAAABQAAAAgBAAQAAAAAAABQAAAAAAABIADAPIABADQAAABABAAQAAAAAAAAQAAABABAAQAAAAAAAAIAUAFIABAAQABAAABAAQAAAAABgBQAAAAAAAAQABAAAAgBIACgDIAHgHQAAAAAAgBQABAAAAAAQAAgBAAAAQAAAAAAgBIgBgCIgFgGIgJgIIgBgBIgCAAgAA7gfIAAAFIABACIACACIAKALIACADQADACADABIAMAEIABAAQABAAAAAAQAAAAAAgBQAAAAAAAAQAAAAAAAAIgBgCQgEgJgHgHIgIgGIAAgBIgIgFIgFgDQgBAAAAABQAAAAgBAAQAAABAAAAQAAABAAABgAgSgHIABAAQAAAAABgBQAAAAABAAQAAAAABgBQAAAAAAgBQAIgIAGgFIAAgBIABgFQgMAKgHAMgAAcgnIgLADIgKAEIgBABIAAAEQgBABAAAAQAAAAAAAAQAAAAABAAQAAAAAAAAIACABQAHAAAJADIACAAIAFAAIAHgCIAOgCIABgBIABgCIABgHIAAAAIgIgCIgMgBIgHAAgAhPhIIADACIADAEIACAEQACAFACACIACACIACABIAEACIAJACIAFACIACADIAHAGQACADAFABIgHgEIgGgHIgBgCIgBgBIgFgDIgJgCIgEgBIgCgBIgBgCIgFgHIgCgEIgDgDIgEgCIgDgBIADABgAgCg3IABAAIABABIAAACIADABIAEABIAEAAIAJAAIAIABIAFAAIADABIACABIAEABIgDgCIgDgBIgBgBIgCgBIgEAAIgWgBIgFgBIgCAAIgBgCgAAiAtQgBgBAAAAQgBgBAAAAQAAgBgBAAQAAgBAAAAQAAgDABgEIAEgJIADgEIAAgBIABABIgCAGQAAAFADACQAAAAABAAQABAAAAAAQABAAAAAAQABAAAAAAIAFgBIAEgCIAQgHIANgHIAGgEIgGAGIgFAGIgGADIgSAMIgIAFIgIABQgDAAgBgBg");
	this.shape_1.setTransform(45,34.6);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(2,6.9,85,38.3);


(lib.block_1_mc = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AryUsMAAAgpYIXlAAMAAAApYg");
	this.shape.setTransform(75.5,132.5);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,151,265);


(lib.block_1_content_mc = function() {
	this.initialize();

	// member_5.png
	this.instance = new lib.member_5();
	this.instance.setTransform(52,106);

	// member_4.png
	this.instance_1 = new lib.member_4();
	this.instance_1.setTransform(17,106);

	// member_3.png
	this.instance_2 = new lib.member_3();
	this.instance_2.setTransform(69,65);

	// member_2.png
	this.instance_3 = new lib.member_2();
	this.instance_3.setTransform(34,65);

	// member_1.png
	this.instance_4 = new lib.member_1();
	this.instance_4.setTransform(0,65);

	// fix
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhsATQAAgrAfghQAhggAsAAQAtAAAgAgQAhAhgBArQABAmgXAdIACgaIgKgKIgDgEIgIAEIgYAHQAAgBgTAEIgHABIgJgBQAGAIgPgIIgagBIgogKIgGgDIAIAJQgJgBgGAGIgEAeQgageABgpg");
	this.shape.setTransform(49.1,9.9);

	// skull
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AAJCmIgIAAIgGAAIgGABQgSAAgPgNQgHgGgIgLIAAAAIAAgBIgFgKQgFgMgEgFQgDgFgCgEIAAgHIAAgGIgBgFIgFgWIgBAAIgCAAIgDgCIgEgCQgJgFgHgPIgFgPQgCgHACgHQABgHAFgCQgFgIgDgTIgBgHIAAgDQgBgCAAgKQABgSAEgOIAFgLQAFgMAIgKQAAgCAGgEIADgCIABAAIABgBIAAgBIAAgBIABAAIAEgIQAQgOAUgIIAEgBIAFgBIACAAIADgBIAGAAIAHgDIAJgDIAIAAQAKAAAJACIAHABIABAAIABAAQAGACADADQAEACAEABIAIABIABABQAPAHANALIAAABIAAAAIAGAHIABAEIACACIACABIABAAIAEADIABABQAVAdAAAmQAAAZgIASIgBAEQAFACABAHQACAHgCAHIgFAPQgHAPgJAFIgDADIgBABIgCABIgCAAIgFAQIgBAJIAAABIAAAGIgBAHQgBAEgEAFQgDAFgFAMIgFAKIgBABQgHALgHAGQgPANgTAAIgFgBgAg7BlIABAJIAEAPIADAGIAAABQAQAaAYAAIAEgBIAHgBIABAAIADABIASAAQASgEANgVIABgBIADgGIABgBIACgOIACgJIAFgEIgCABIgBAFIgBAJIAFgIIADgGIABgFIAAgHIAFgYIgBAAIgIAAQgDABgBACQgEAGgBAKIgBgEQAAgEADgGQAAgBAAgBQAAAAAAAAQAAgBAAAAQAAAAgBAAQgEADgBAEIgBANIAAAHIgCABIgDAFIgDAJIgBAEIgBABIgCADIAAABIgCADIAAABQAAABAAAAQgBABAAAAQAAAAgBABQAAAAgBAAIAAgGIAAAAQgBAAAAAAQAAAAgBAAQAAAAAAABQAAAAgBAAIgCADIAAAFIAAgFQAAAAgBAAQAAAAAAAAQgBAAAAAAQAAAAgBAAIgCABQgDACAAADQAAABAAAAQAAABABABQAAAAAAAAQAAABAAAAIACAAQAEgCABgDIABAAQABAAAAgBQABAAAAAAQABAAAAgBQAAAAABgBIAAACQAAAAgBABQAAAAAAABQAAAAgBAAQAAABgBAAIgCAIIgBgBIABgGQgBADgEABQgEAGAAAFIAAAAQgBgDABgFIgDACQgEACgCAAIgBABIgCAJIAAgGIAAgCIgEACQgGACAAgFQgBAFgEgCIgEgCQAAAAAAAAQAAAAAAAAQAAABAAAAQAAAAAAABIAAAGIgCgJIgBgBQgCAAgEgCIgCgCQABAHgCABQAAgEgEgHQgDgBgBgCIAAAGIgDgIIgCgCIgBgBIAAgCQAAAAABABQAAAAABABQAAAAABAAQAAABABAAIABgBIAAgEIgCgDIgDgBIAAADIAAACIAAABIgBAAIgCgCIAAgBIAAgBIgCgDIAAgCIgCgCIgBgBIgBgEIgDgJIgDgFIgCgBIgBgTIgCgFQgHgGACAGQADAJgBAFQgCgKgDgGQgBgCgDgBIgHAAIgBAAIAFAXIAAABIAAAHIAAACIABAEIADAFIAFAIIgBgJQAAgBAAAAQAAgBgBgBQAAAAAAgBQAAAAgBgBIgBgBIAFAEgAACCAIgBADIAAAHQABAEAFgCIACgBQAEgCgBgGQAAgBAAgBQAAAAgBgBQAAAAgBgBQAAAAgBAAIgCAAIgFABgAgGB/QgBAAAAAAQgBABAAAAQgBABAAAAQAAABAAABQgBAGAEACIACABQAEACAAgEIAAgHIAAgDIgEgBIgCAAgAASB8QgBAAAAAAQgBAAAAABQgBAAAAAAQAAABgBAAIgBAFIABADQAAABAAAAQAAAAAAABQAAAAAAAAQAAAAABAAIABAAIAEgCIACgBQACgCAAgFQAAgBgBAAQAAAAAAgBQAAAAgBAAQAAAAAAAAIgCAAIgCAAgAgTB8QAAAAAAAAQgBAAAAAAQAAABAAAAQAAAAAAABQAAAFABACIACABIAEACIABAAQAAAAABAAQAAAAAAAAQAAgBAAAAQABAAAAgBIAAgDIgBgFQAAAAgBgBQAAAAgBAAQAAgBgBAAQAAAAgBAAIgCAAIgCAAgAgdB4IAAAFQACADADACIACAAIABgCIAAgCQAAgDgDgCIgCgBIgCAAIgBAAgAgLBzQABADAFABQAFABABgCIAAAAQABAAAAAAQABABAAAAQABAAAAAAQABAAABAAIAFgBQAAAAABAAQAAgBABAAQAAAAAAgBQABAAAAgBIAAgBQABACAGgCQABAAAAAAQABgBAAAAQABAAAAgBQABAAAAgBIAAgDIAAgGQgBAAAAAAQAAgBgBAAQAAAAgBAAQAAAAgBAAQgEAAgBACIgCADIAAAIIAAgJIgDgBIgCgBIgBAAIgDABQgDABgBAEIAAAJIAAgCIAAgDQgBgIgCgBIgDgBIgBABQgEAAgBAGIAAgCIgCgEQAAgBgBAAQAAgBgBAAQAAAAgBgBQAAAAgBAAIgBAAQgBAAAAAAQgBAAAAAAQgBAAAAABQgBAAAAAAIAAgBIgBgBIgCgDIgBAAIgBABQgBAAAAAAQgBAAAAABQAAAAAAABQAAAAAAABIABAHIgCgHIAAgDIAAgEIgBAAIgBAAIgBAAIgBADIAAgDQAAgBAAAAQAAgBAAAAQAAAAAAgBQAAAAgBAAIgBgBIgBAAQAAABAAAAQgBAAAAABQAAAAAAAAQAAABAAAAIAAADIABADIgBgBIACACIABgBIABgBIAAAFQAAABAAAAQABABAAAAQAAABABAAQAAABABAAIACAAIAAABIAAgBIABACIACABIADAAIABgCIAAgCIAAAFQABACAEABIADABQABAAAAAAQABAAAAgBQAAAAAAAAQABAAAAgBgAAlBwIABAHQAAAAABAAQAAgBABAAQAAAAAAgBQABAAAAgBIAAgGIgBAAQgBAAAAAAQAAAAgBABQAAAAAAAAQAAABgBAAgAgmBuIAAAGIABABQAAABAAAAQABAAAAAAQAAABABAAQAAAAAAAAIABgDIgBgEQAAgBAAAAQAAAAgBgBQAAAAAAAAQAAAAgBAAIgBAAgAAZBlIAAAGIABABQAAABAAABQAAAAAAAAQABABAAAAQABAAABgBQAAAAABAAQAAAAABgBQAAAAABAAQAAgBAAAAIABgBIAAAAIADgCIABgCIABgEIgBgFIgCAAIgBAAIAAAAIgBAEIAAADIgBAGIAAgGQAAgBAAgBQAAAAAAgBQgBAAAAAAQgBgBAAAAIgBAAQgDABgBADgAABBmIABAAQACgBAEgBIABAAIADABQABgEgCgHQADADACAHQAAgBABAAQAAAAABgBQAAAAABAAQAAAAABAAIADAAQAAgEgBgDIABABIADAFIACgDIACAAIgCgFIACABIACADIABgCQAAAAAAAAQABgBAAAAQABAAAAAAQAAAAABABIABgEIACAAIABgFQABgHAEgDIgEAAIACgCIAFgDQAGgDACgCQgCgCgFABIgBAAIgKADIgEADQAFgHAMgCQAIgBALACIAEgBIAAgBIgEgBIgDgBIAFABIAGAAIACgCIABgDIABgEQAAgEACgCIACgCQgCACAAADIABAEIAAACIAAADQADgEAEgCQAFgCAFgLQAEgIACgHQABgFgBgFQgBgFgDgBQgEgCADgJIAAgBQAIgTAAgVQAAgJgCgIIgLgOIgSAPIAEAfIAMAMIgBACIgMgMIgKAOIAEgDQgDAFgFAEIABAAQAGABADADIACADQADAFABAGIABALQABAEgCAFIAEgEQgDAJgHAFIgHADIgBAAQgQAFgTgIIgNgGIABACQACACAAAFQgGgEgDgJIAAgBIgBAAIgBgMIAAgIQAAgIAEgDIgTgIIgOAIQAGACAAAJIAAAIIgCAMIAAABQgDAJgGAEQAAgFACgCIABgCIgNAGQgTAIgRgFIgDAAIgHgDQgHgFgDgJIACADIAGAEQgDgGABgGIABgLQABgGADgFIACgDQADgDAGgBIgGgGIgDgDIADACIgJgRIgNAOIgCgCIAOgPIACgdIgQgOIgNAQIgCARQAAAVAIATIABABIAAAHQAAACgCACQgDABgBAFQgBAFABAFQACAHAEAIQAFALAFACQAFACACAEIAAgDIABgCIAAgEQAAgDgCgCIACACQADACAAAEIAAABIAAADIABADQAAABABAAQAAABAAAAQABAAAAAAQAAAAABAAIAFAAIAFgBIgDABIgEABIAAABIACABQAMgCAHABQAOABAFAIQgGgEgIgCIgBAAIgFAAIgCABIACACIAGADQAGACABADIgDAAIAAAAQADADACAHIAAAFIACAAIABAEQABgBAAAAQAAAAABAAQAAAAAAABQABAAAAAAIABACIADgDIABgBQgCADAAACIACAAIADADIACgFIABgBQgBADABAEIACAAQAAAAABAAQABAAAAAAQABABAAAAQABAAAAABQACgHADgDIgBAEIAAAHIADgBIABAAIAFACIABgGgAAnBaIgBABIgBADIAAABIABADIAAABIABABQAAAAAAAAQABAAAAAAQAAgBABAAQAAgBAAgBIABgBIAAgDIgBgCQAAgBgBAAQAAAAAAAAQAAgBgBAAQAAAAAAAAgAAhAMQgDAEABADQADADAJgDIAfgLIgfAHQgEABgCgBQgBgBAAAAQAAAAgBgBQAAAAAAgBQAAgBAAAAIACgDIgEAEgAABhDIAAAxIAYALQAGAAAJgCQAQgDAMgEIANgSIgEgfIghgWgAhKhEIgCAdIALAWIAQAFIAFABQARAEAHAAIASgJIACgBIAAgNIAAglIgpgWgAAfiBIAOAoIAhAWIATgPIgKghIgFgFIglgRgAgnhbIAnAWIAqgTIgOgoIgxAAgAhPh4IgNAkIARAOIAhgVIASgmIgRgJgABjhSIAJALQgEgVgNgSIABADIgBAAgAhphHIAKgNIAMggQgRAUgFAZgAhMh8IAigQIAPgMQgcAIgVAUgABOh8IAAgBQgSgRgZgIIALALIAgAPgAgTiaIgUAPIARAIIAzAAIAOgIIgNgNQgOgEgPAAQgKAAgKACgAARBPIgBgCQgFAAgDgCIgCgDIABABIAFACIAEAAQAEgBABgDQgBAFgCABIABAFIgCgDgAgPBNQgDgBAAgFIABACQAAAAABABQAAAAAAAAQABABAAAAQABAAAAAAIAFAAIAEgCIAFgCIAAgBIgDAEIgFADQgCABgEgBIgBACIgCADIACgFgAAKBHIgGgFIgDgBIgCABIgGAFQgFADgBgEIgBgFQACgPAFgKQAEgGACgBQABAAAAAAQAAABAAAAQAAAAAAABQAAABAAAAQAAABAAAAQAAAAAAAAQAAABAAAAQAAAAAAAAIACAAQAAAAAAAAQAAAAABgBQAAAAAAAAQAAAAAAgBIABgDQACABAEAGQAFAKACAPIAAAFQAAAAgBABQAAAAAAAAQgBABAAAAQgBAAAAAAIgEgBg");
	this.shape_1.setTransform(49,16.7);

	// txt
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAVAgQgEgCgCgCQgCgCgBgDIgBgHIAAgfIABgGQABgEACgCQACgDAEAAQADgCAEAAQAEAAAEACIAFADIADAGIABAHIAAAEIgLAAIAAgEQAAgFgCgBIgEgCQgBAAAAAAQgBAAgBAAQAAABgBAAQAAAAAAABQgCACAAADIAAAfQAAAEACACQAAAAAAAAQABAAAAABQABAAABAAQAAAAABAAQABAAABAAQAAAAABAAQAAgBABAAQAAAAAAAAQACgDAAgDIAAgHIALAAIAAAHIgBAHQgBADgCACQgCACgDACQgEABgEAAQgEAAgDgBgACkAgIgIgpIgIApIgJAAIgMg/IAKAAIAHAnIAHgnIAKAAIAHAnIAHgnIAKAAIgLA/gABfAgIAAg/IAeAAIAAAKIgTAAIAAARIAPAAIAAAHIgPAAIAAAUIAUAAIAAAJgABOAgIgIgbIgDAAIgDAAIAAAbIgLAAIAAg/IAQAAIAIABQAEABACACQAFAFAAAKIgBAHIgCAEIgCACIgDACIAJAdgABAgCIAEAAIAEAAQABAAAAgBQAAAAABAAQAAAAAAAAQAAgBABAAIABgDIABgFQAAgFgCgDIgDgBIgEgBIgEAAgAgpAgIAAg/IAeAAIAAAKIgTAAIAAARIAPAAIAAAHIgPAAIAAAUIAUAAIAAAJgAhFAgIgNg/IALAAIAIArIAIgrIALAAIgOA/gAhcAgIgCgPIgMAAIgCAPIgLAAIAMg/IAOAAIAMA/gAhpAIIAJAAIgEgagAiYAgIAAg/IAeAAIAAAKIgTAAIAAARIAPAAIAAAHIgPAAIAAAUIAUAAIAAAJgAi4AgIAAg/IALAAIAAA2IARAAIAAAJg");
	this.shape_2.setTransform(48.8,198.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#4AC8EB").s().p("ACmA1QgFgCgEgEQgDgEgCgFQgCgFAAgFIAAg2IACgLQACgFADgEQAEgEAFgCQAFgCAIAAQAGAAAFACQAGADADAEQADAEADAFQABAGAAAGIAAAIIgSAAIAAgJQgBgHgCgDQgDgDgDAAQgGAAgCADQgCADAAAGIAAA1QAAAGACADQACADAGAAQAFAAACgDQACgDAAgFIAAgNIASAAIAAANQAAAFgBAFIgGAJQgDAEgGACQgFACgGAAQgIAAgFgCgABXA2IAAhrIAzAAIAAARIghAAIAAAcIAZAAIAAAOIgZAAIAAAwgAAZA2IgYhCIAABCIgPAAIAAhrIAPAAIAXA8IAAg8IARAAIAABrgAg7A2IAAhaIgSAAIAAgRIA3AAIAAARIgSAAIAABagAh2A2IgXhrIASAAIAOBKIABAAIANhKIASAAIgWBrgAjNA2IAAhrIAbAAQAIAAAGACQAFACAEAEQADADABAGQACAFAAAHIgBAHIgBAHIgEAFIgGAEIAGACIAEAFQAEAGABAKQAAAHgCAGQgBAGgEAEQgDAEgGACQgFADgJAAgAi7AmIAIAAQAIAAADgEQADgEAAgIQAAgJgEgEQgDgEgIAAIgHAAgAi7gIIAIAAQAEAAAEgEQAEgDAAgHQAAgPgMAAIgIAAg");
	this.shape_3.setTransform(49.1,48.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#1B1B1B").s().p("ADOAgIgGgFIgDgFIgBgHIAKgBQAAAEADADQAAAAAAABQABAAAAAAQABABABAAQAAAAABAAQABAAAAAAQABAAAAAAQABgBAAAAQABAAABAAQAAgBAAAAQABgBAAAAQAAgBAAgBQAAAAAAgBQAAgDgBgCIgEgGIgGgEIgGgDIgDgHQgCgDAAgFIABgGIADgGQAEgEAJAAQADAAADACIAFACIADAGIABAGIgKABIgBgEIgBgBIgCgCIgCAAQgBAAAAAAQgBAAgBAAQAAABgBAAQAAAAAAABQgBAAAAAAQAAABgBAAQAAABAAABQAAAAAAABQAAADACADIAEAEIAFAFIAGADIAEAGQACAEAAAEQAAAFgCACQAAADgDADIgGADIgHABQgDAAgDgBgACcAgIAAg/IARAAIAIABQADABACADQAEAEAAALIAAAYQAAAKgEAEQgCACgDACIgIABgACnAXIAFAAQAEAAACgCQACgCAAgFIAAgaQAAgGgCgCQgCgCgEAAIgFAAgACLAgIgOgnIAAAnIgKAAIAAg/IAKAAIANAjIAAgjIAKAAIAAA/gABNAgIAAg/IAfAAIAAAKIgTAAIAAARIAOAAIAAAHIgOAAIAAAUIAUAAIAAAJgAA5AgIAAg/IALAAIAAA/gAAmAgIgIgbIgCAAIgDAAIAAAbIgMAAIAAg/IAQAAIAIABQAEABACACQAFAFAAAKIgBAHIgBAEIgDACIgDACIAJAdgAAZgCIADAAIAEAAQABAAAAgBQABAAAAAAQAAAAAAAAQABgBAAAAIACgDIAAgFQAAgFgCgDIgDgBIgEgBIgDAAgAgWAgIAAg/IAeAAIAAAKIgTAAIAAARIANAAIAAAHIgNAAIAAAdgAhMAgIAAg/IAfAAIAAAKIgUAAIAAARIAPAAIAAAHIgPAAIAAAUIAVAAIAAAJgAhlAgIAAg1IgLAAIAAgKIAhAAIAAAKIgLAAIAAA1gAiAAgIAAg/IALAAIAAA/gAieAgIgNg/IALAAIAIArIAIgrIALAAIgOA/gAi4AgIgOgnIAAAnIgLAAIAAg/IALAAIANAjIAAgjIAKAAIAAA/gAjlAgIAAg/IALAAIAAA/g");
	this.shape_4.setTransform(48.9,171.8);

	// button shapes
	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f().s("#1B1B1B").ss(1,1,1).p("AJxgYIzhAAIAAjcIThAAgAJxD1IzhAAIAAjcIThAAg");
	this.shape_5.setTransform(49.5,185.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#1B1B1B").s().p("ApvBtIAAjZITfAAIAADZg");
	this.shape_6.setTransform(49.5,199);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("ApvBtIAAjZITfAAIAADZg");
	this.shape_7.setTransform(49.5,172);

	this.addChild(this.shape_7,this.shape_6,this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape,this.instance_4,this.instance_3,this.instance_2,this.instance_1,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-12.9,0,125,210);


(lib.block_6_anim_mc = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.block_6_content_mc();
	this.instance.setTransform(76.6,65,1,1,0,0,0,58.6,36);

	this.instance_1 = new lib.block_6_mc();

	this.addChild(this.instance_1,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,151,265);


(lib.block_1_anim_mc = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.startMenu_mc();
	this.instance.setTransform(77.5,20.6,1,1,0,0,0,68.4,6.8);

	this.instance_1 = new lib.block_1_content_mc();
	this.instance_1.setTransform(76.5,153.6,1,1,0,0,0,49.5,105.5);

	this.instance_2 = new lib.block_1_mc();
	this.instance_2.setTransform(75.5,132.5,1,1,0,0,0,75.5,132.5);

	this.addChild(this.instance_2,this.instance_1,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,151,265);


(lib.MC_Banner = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{part1:1,part2:18,part3:56,part4:94,part5:129,part6:154,part7:171,part8:193,part9:225});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_1 = function() {
		this.visible = true;
	}
	this.frame_17 = function() {
		this.stop();
	}
	this.frame_55 = function() {
		this.stop();
	}
	this.frame_93 = function() {
		this.stop();
	}
	this.frame_128 = function() {
		this.stop();
	}
	this.frame_153 = function() {
		this.stop();
	}
	this.frame_170 = function() {
		this.stop();
	}
	this.frame_192 = function() {
		this.stop();
	}
	this.frame_224 = function() {
		this.stop();
	}
	this.frame_256 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1).call(this.frame_1).wait(16).call(this.frame_17).wait(38).call(this.frame_55).wait(38).call(this.frame_93).wait(35).call(this.frame_128).wait(25).call(this.frame_153).wait(17).call(this.frame_170).wait(22).call(this.frame_192).wait(32).call(this.frame_224).wait(32).call(this.frame_256));

	// menuBar2_mc
	this.instance = new lib.menuBar2_mc();
	this.instance.setTransform(76.2,19.8,1,1,0,0,0,67.5,3.4);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(171).to({_off:false},0).wait(22).to({y:-114.7},8,cjs.Ease.get(-0.74)).to({y:-248},23,cjs.Ease.get(1)).wait(33));

	// statusBarWhite_mc
	this.instance_1 = new lib.statusBarWhite_mc();
	this.instance_1.setTransform(76.4,6.2,1,1,0,0,0,72.4,5.2);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(171).to({_off:false},0).to({alpha:0.469},8,cjs.Ease.get(-0.74)).to({alpha:1},13,cjs.Ease.get(1)).wait(1).to({y:-128},8,cjs.Ease.get(-0.74)).to({y:-261.6},23,cjs.Ease.get(1)).wait(33));

	// statusBar_mc
	this.instance_2 = new lib.statusBar_mc();
	this.instance_2.setTransform(76.4,6.2,1,1,0,0,0,72.4,5.2);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({_off:true},193).wait(64));

	// Layer 3
	this.instance_3 = new lib.reel_mc();
	this.instance_3.setTransform(226.5,363.5,1,1,0,0,0,75.5,363.5);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(171).to({_off:false},0).to({x:151},8,cjs.Ease.get(-0.74)).to({x:75.5},13,cjs.Ease.get(1)).wait(1).to({y:229.5},8,cjs.Ease.get(-0.74)).to({y:95.5},23,cjs.Ease.get(1)).wait(1).to({y:-1.3},8,cjs.Ease.get(-0.74)).to({y:-98.3},23,cjs.Ease.get(1)).wait(1));

	// block_1_anim_mc
	this.instance_4 = new lib.block_1_anim_mc();
	this.instance_4.setTransform(75.5,132.5,1,1,0,0,0,75.5,132.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(1).to({y:265},8,cjs.Ease.get(-0.74)).to({y:397.5},8,cjs.Ease.get(1)).to({_off:true},1).wait(239));

	// menuBar_mc
	this.instance_5 = new lib.menuBar_mc();
	this.instance_5.setTransform(76.2,19.8,1,1,0,0,0,67.5,3.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_5}]}).wait(257));

	// touch_mc
	this.instance_6 = new lib.touch_mc();
	this.instance_6.setTransform(76,254,0.9,0.9,0,0,0,10,10);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(94).to({_off:false},0).to({scaleX:2,scaleY:2,alpha:0},18).to({_off:true},1).wait(16).to({scaleX:0.9,scaleY:0.9,alpha:1,_off:false},0).to({scaleX:2,scaleY:2,alpha:0},18).wait(110));

	// footer_1234_mc
	this.instance_7 = new lib.footer_1_mc();
	this.instance_7.setTransform(0,242);

	this.instance_8 = new lib.footer_2_mc();
	this.instance_8.setTransform(0,242);

	this.instance_9 = new lib.footer_3_mc();
	this.instance_9.setTransform(0,242);

	this.instance_10 = new lib.footer_4_mc();
	this.instance_10.setTransform(0,242);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_7}]}).to({state:[{t:this.instance_8}]},98).to({state:[{t:this.instance_9}]},35).to({state:[{t:this.instance_10}]},25).wait(99));

	// block_6_anim_mc
	this.instance_11 = new lib.block_6_anim_mc();
	this.instance_11.setTransform(75.5,397.5,1,1,0,0,0,75.5,132.5);
	this.instance_11._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(102).to({_off:false},0).to({y:265},8,cjs.Ease.get(-0.74)).to({y:132.5},18,cjs.Ease.get(1)).wait(9).to({y:265},8,cjs.Ease.get(-0.74)).to({y:397.5},8,cjs.Ease.get(1)).wait(104));

	// member_1_mc
	this.instance_12 = new lib.member_1_mc();
	this.instance_12.setTransform(62.9,65.4,1,1,0,0,0,20.9,19.4);
	this.instance_12._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(129).to({_off:false},0).wait(25).to({x:42.9},8,cjs.Ease.get(1)).wait(95));

	// member_2_mc
	this.instance_13 = new lib.member_2_mc();
	this.instance_13.setTransform(98.9,64,1,1,0,0,0,19.4,18);
	this.instance_13._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(129).to({_off:false},0).wait(25).to({x:80.4},8,cjs.Ease.get(1)).wait(95));

	// member_3_mc
	this.instance_14 = new lib.member_3_mc();
	this.instance_14.setTransform(96.1,62.6,1,1,0,0,0,16.6,16.6);
	this.instance_14._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_14).wait(154).to({_off:false},0).to({x:115.6},8,cjs.Ease.get(1)).wait(95));

	// block_7_content_mc
	this.instance_15 = new lib.block_7_content_mc();
	this.instance_15.setTransform(73.6,52.2,1,1,0,0,0,50.6,41.2);
	this.instance_15._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_15).wait(129).to({_off:false},0).wait(128));

	// block_7_initials_mc
	this.instance_16 = new lib.block_7_initials_now_mc();
	this.instance_16.setTransform(77.9,90.6,1,1,0,0,0,16.8,5.6);
	this.instance_16._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_16).wait(129).to({_off:false},0).wait(128));

	// block_7_mc
	this.instance_17 = new lib.block_7_mc();
	this.instance_17.shadow = new cjs.Shadow("rgba(0,0,0,0.2)",0,0,5);
	this.instance_17._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_17).wait(129).to({_off:false},0).wait(128));

	// block_8_content_mc
	this.instance_18 = new lib.block_8_content_mc();
	this.instance_18.setTransform(75.5,60,1,1,0,0,0,44.4,16.5);
	this.instance_18._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_18).wait(154).to({_off:false},0).to({y:135},8,cjs.Ease.get(0.75)).to({y:130},4,cjs.Ease.get(-0.49)).to({y:125},4,cjs.Ease.get(1)).wait(87));

	// block_8_initials_mc
	this.instance_19 = new lib.block_8_initials_now_mc();
	this.instance_19.setTransform(77.9,87.6,1,1,0,0,0,16.8,5.6);
	this.instance_19._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_19).wait(154).to({_off:false},0).to({y:162.6},8,cjs.Ease.get(0.75)).to({y:157.6},4,cjs.Ease.get(-0.49)).to({y:152.6},4,cjs.Ease.get(1)).wait(87));

	// block_8_mc
	this.instance_20 = new lib.block_8_mc();
	this.instance_20.setTransform(0,36);
	this.instance_20._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_20).wait(154).to({_off:false},0).to({scaleY:1.15,y:101},8,cjs.Ease.get(0.75)).to({scaleY:1.08},4,cjs.Ease.get(-0.49)).to({scaleY:1},4,cjs.Ease.get(1)).wait(87));

	// block_5_content_mc
	this.instance_21 = new lib.block_5_content_mc();
	this.instance_21.setTransform(76,-46.3,1,1,0,0,0,17,27.1);
	this.instance_21._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_21).wait(74).to({_off:false},0).to({y:-15.2},5).to({y:64.6},6,cjs.Ease.get(0.5)).to({y:59.6},4,cjs.Ease.get(-0.49)).to({y:54.6},4,cjs.Ease.get(1)).wait(36).to({scaleX:0.75,scaleY:0.75,x:76.8,y:129.4},0).wait(25).to({scaleX:0.65,scaleY:0.65,x:75.8,y:201.1},8,cjs.Ease.get(0.75)).to({y:196.1},4,cjs.Ease.get(-0.49)).to({y:191.1},4,cjs.Ease.get(1)).wait(87));

	// block_5_initials_mc 6secs
	this.instance_22 = new lib.block_2_initials_4secs_mc();
	this.instance_22.setTransform(77.9,214.6,1,1,0,0,0,16.8,5.6);
	this.instance_22._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_22).wait(170).to({_off:false},0).wait(87));

	// block_5_initials_mc 4secs
	this.instance_23 = new lib.block_2_initials_4secs_mc();
	this.instance_23.setTransform(77.9,154.6,1,1,0,0,0,16.8,5.6);
	this.instance_23._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_23).wait(129).to({_off:false},0).wait(25).to({y:224.6},8,cjs.Ease.get(0.75)).to({y:219.6},4,cjs.Ease.get(-0.49)).to({y:214.9},3,cjs.Ease.get(1)).to({_off:true},1).wait(87));

	// block_5_initials_mc now
	this.instance_24 = new lib.block_2_initials_4secs_mc();
	this.instance_24.setTransform(77.9,-10.3,1,1,0,0,0,16.8,5.6);
	this.instance_24._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_24).wait(74).to({_off:false},0).to({y:20.6},5).to({y:100.6},6,cjs.Ease.get(0.5)).to({y:95.6},4,cjs.Ease.get(-0.49)).to({y:90.6},4,cjs.Ease.get(1)).to({_off:true},36).wait(128));

	// block_5_mc
	this.instance_25 = new lib.block_5_mc();
	this.instance_25.setTransform(0,-100.9);
	this.instance_25._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_25).wait(74).to({_off:false},0).to({y:-69.8},5).to({scaleY:1.1,y:0},6,cjs.Ease.get(0.5)).to({scaleY:1.05},4,cjs.Ease.get(-0.49)).to({scaleY:1},4,cjs.Ease.get(1)).wait(36).to({scaleY:0.64,y:101},0).wait(25).to({scaleY:0.59,y:176},8,cjs.Ease.get(0.75)).to({y:171},4,cjs.Ease.get(-0.49)).to({scaleY:0.6,y:166},4,cjs.Ease.get(1)).wait(87));

	// block_4_content_mc
	this.instance_26 = new lib.block_4_content_mc();
	this.instance_26.setTransform(75.1,-56,1.1,1.1,0,0,0,59.3,18);
	this.instance_26._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_26).wait(36).to({_off:false},0).to({y:-20.9},5).to({y:55.4},6,cjs.Ease.get(0.5)).to({y:50.4},4,cjs.Ease.get(-0.49)).to({y:45.4},4,cjs.Ease.get(1)).wait(1).to({y:60.5},6,cjs.Ease.get(-0.99)).to({y:75.4},12,cjs.Ease.get(1)).wait(5).to({scaleX:1,scaleY:1,y:140.4},6,cjs.Ease.get(0.5)).to({y:135.4},4,cjs.Ease.get(-0.49)).to({y:130.4},4,cjs.Ease.get(1)).wait(36).to({y:188.4},0).wait(25).to({regX:59.2,scaleX:0.4,scaleY:0.4,x:25.1,y:250.6},8,cjs.Ease.get(0.75)).to({y:245.6},4,cjs.Ease.get(-0.49)).to({y:240.6},4,cjs.Ease.get(1)).wait(87));

	// block_4_initials_mc 10secs
	this.instance_27 = new lib.block_4_initials_now_mc();
	this.instance_27.setTransform(76.9,215.6,1,1,0,0,0,16.8,5.6);
	this.instance_27._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_27).wait(129).to({_off:false},0).wait(25).to({x:26.8,y:275.2},8,cjs.Ease.get(0.75)).to({y:270.1},4,cjs.Ease.get(-0.49)).to({y:265},4,cjs.Ease.get(1)).wait(87));

	// block_4_initials_mc 2secs
	this.instance_28 = new lib.block_4_initials_now_mc();
	this.instance_28.setTransform(76.9,155.6,1,1,0,0,0,16.8,5.6);
	this.instance_28._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_28).wait(93).to({_off:false},0).to({_off:true},36).wait(128));

	// block_4_initials_mc now
	this.instance_29 = new lib.block_4_initials_now_mc();
	this.instance_29.setTransform(76.9,-20.8,1,1,0,0,0,16.8,5.6);
	this.instance_29._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_29).wait(36).to({_off:false},0).to({y:14.1},5).to({y:90.6},6,cjs.Ease.get(0.5)).to({y:85.6},4,cjs.Ease.get(-0.49)).to({y:80.6},4,cjs.Ease.get(1)).wait(1).to({y:95.6},6,cjs.Ease.get(-0.99)).to({y:110.6},12,cjs.Ease.get(1)).wait(5).to({y:165.6},6,cjs.Ease.get(0.5)).to({y:160.6},4,cjs.Ease.get(-0.49)).to({y:155.9},3,cjs.Ease.get(1)).to({_off:true},1).wait(164));

	// block_4_mc
	this.instance_30 = new lib.block_4_mc();
	this.instance_30.setTransform(0,-101.4);
	this.instance_30._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_30).wait(36).to({_off:false},0).to({y:-66.3},5).to({scaleY:1.1,y:0},6,cjs.Ease.get(0.5)).to({scaleY:1.05},4,cjs.Ease.get(-0.49)).to({scaleY:1},4,cjs.Ease.get(1)).wait(1).to({y:15},6,cjs.Ease.get(-0.99)).to({y:30},12,cjs.Ease.get(1)).wait(5).to({scaleY:0.64,y:111},6,cjs.Ease.get(0.5)).to({y:106},4,cjs.Ease.get(-0.49)).to({y:101},4,cjs.Ease.get(1)).wait(36).to({scaleY:0.6,y:166},0).wait(25).to({scaleX:0.33,scaleY:0.5,y:236},8,cjs.Ease.get(0.75)).to({y:231},4,cjs.Ease.get(-0.49)).to({y:226},4,cjs.Ease.get(1)).wait(87));

	// block_3_content_mc
	this.instance_31 = new lib.block_3_content_mc();
	this.instance_31.setTransform(75.7,73.2,1,1,0,0,0,47.5,25.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_31).wait(18).to({y:90.7},6,cjs.Ease.get(-0.99)).to({y:108.2},12,cjs.Ease.get(1)).wait(5).to({scaleX:0.7,scaleY:0.7,y:138.2},6,cjs.Ease.get(0.5)).to({y:131.7},4,cjs.Ease.get(-0.49)).to({y:125.2},4,cjs.Ease.get(1)).wait(1).to({y:140.2},6,cjs.Ease.get(-0.99)).to({y:155.2},12,cjs.Ease.get(1)).wait(5).to({regY:25.6,scaleX:0.6,scaleY:0.6,y:201.2},6,cjs.Ease.get(0.5)).to({y:196.2},4,cjs.Ease.get(-0.49)).to({regY:25.5,y:191.2},4,cjs.Ease.get(1)).wait(36).to({scaleX:0.4,scaleY:0.4,x:25.7,y:243.6},0).wait(25).to({x:75.7,y:253.6},8,cjs.Ease.get(0.75)).to({y:248.6},4,cjs.Ease.get(-0.49)).to({y:243.6},4,cjs.Ease.get(1)).wait(87));

	// block_3_initials_mc 6secs
	this.instance_32 = new lib.block_3_initials_now_mc();
	this.instance_32.setTransform(76.9,217.6,1,1,0,0,0,16.8,5.6);
	this.instance_32._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_32).wait(93).to({_off:false},0).wait(36).to({x:26.9,y:265.1},0).wait(25).to({x:76.9,y:275.1},8,cjs.Ease.get(0.75)).to({y:270.1},4,cjs.Ease.get(-0.49)).to({y:265.1},4,cjs.Ease.get(1)).wait(87));

	// block_3_initials_mc 4secs
	this.instance_33 = new lib.block_3_initials_now_mc();
	this.instance_33.setTransform(76.9,155.6,1,1,0,0,0,16.8,5.6);
	this.instance_33._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_33).wait(55).to({_off:false},0).wait(1).to({y:170.6},6,cjs.Ease.get(-0.99)).to({y:185.6},12,cjs.Ease.get(1)).wait(5).to({y:227.6},6,cjs.Ease.get(0.5)).to({y:222.6},4,cjs.Ease.get(-0.49)).to({y:217.9},3,cjs.Ease.get(1)).to({_off:true},1).wait(164));

	// block_3_initials_mc now
	this.instance_34 = new lib.block_3_initials_now_mc();
	this.instance_34.setTransform(76.9,110.6,1,1,0,0,0,16.8,5.6);

	this.timeline.addTween(cjs.Tween.get(this.instance_34).wait(18).to({y:128.1},6,cjs.Ease.get(-0.99)).to({y:145.6},12,cjs.Ease.get(1)).wait(5).to({y:168.6},6,cjs.Ease.get(0.5)).to({y:162.1},4,cjs.Ease.get(-0.49)).to({y:156},3,cjs.Ease.get(1)).to({_off:true},1).wait(202));

	// block_3_mc
	this.instance_35 = new lib.block_3_mc();

	this.timeline.addTween(cjs.Tween.get(this.instance_35).wait(18).to({y:17.5},6,cjs.Ease.get(-0.99)).to({y:35},12,cjs.Ease.get(1)).wait(5).to({scaleY:0.55,y:111},6,cjs.Ease.get(0.5)).to({scaleY:0.53,y:106},4,cjs.Ease.get(-0.49)).to({scaleY:0.5,y:101},4,cjs.Ease.get(1)).wait(1).to({y:116},6,cjs.Ease.get(-0.99)).to({y:131},12,cjs.Ease.get(1)).wait(5).to({scaleY:0.47,y:176},6,cjs.Ease.get(0.5)).to({y:171},4,cjs.Ease.get(-0.49)).to({scaleY:0.47,y:166},4,cjs.Ease.get(1)).wait(36).to({scaleX:0.33,scaleY:0.39,y:226},0).wait(25).to({x:50,y:236},8,cjs.Ease.get(0.75)).to({y:231},4,cjs.Ease.get(-0.49)).to({y:226},4,cjs.Ease.get(1)).wait(87));

	// block_2_content_mc
	this.instance_36 = new lib.block_2_content_mc();
	this.instance_36.setTransform(75.5,163.7,1,1,0,0,0,45,14.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_36).wait(18).to({scaleX:0.95,scaleY:0.95,y:176.2},6,cjs.Ease.get(-0.99)).to({scaleX:0.9,scaleY:0.9,y:188.7},12,cjs.Ease.get(1)).wait(5).to({scaleX:0.7,scaleY:0.7,x:75.4,y:198.2},6,cjs.Ease.get(0.5)).to({y:190.2},4,cjs.Ease.get(-0.49)).to({y:182.2},4,cjs.Ease.get(1)).wait(1).to({y:197.2},6,cjs.Ease.get(-0.99)).to({y:212.2},12,cjs.Ease.get(1)).wait(5).to({scaleX:0.4,scaleY:0.4,x:25.4,y:249.2},6,cjs.Ease.get(0.5)).to({y:244.2},4,cjs.Ease.get(-0.49)).to({y:239.2},4,cjs.Ease.get(1)).wait(36).to({x:75.4},0).wait(25).to({x:125.4,y:249.2},8,cjs.Ease.get(0.75)).to({y:244.2},4,cjs.Ease.get(-0.49)).to({y:239.2},4,cjs.Ease.get(1)).wait(87));

	// block_2_initials_mc 10secs
	this.instance_37 = new lib.block_2_initials_4secs_mc();
	this.instance_37.setTransform(76.9,215.1,1,1,0,0,0,16.8,5.6);
	this.instance_37._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_37).wait(55).to({_off:false},0).wait(1).to({y:230.1},6,cjs.Ease.get(-0.99)).to({y:245.1},12,cjs.Ease.get(1)).wait(5).to({x:26.9,y:275.1},6,cjs.Ease.get(0.5)).to({y:270.1},4,cjs.Ease.get(-0.49)).to({y:265.1},4,cjs.Ease.get(1)).wait(36).to({x:76.9},0).wait(25).to({x:126.9,y:275.1},8,cjs.Ease.get(0.75)).to({y:270.1},4,cjs.Ease.get(-0.49)).to({y:265.1},4,cjs.Ease.get(1)).wait(87));

	// block_2_initials_mc 4secs
	this.instance_38 = new lib.block_2_initials_4secs_mc();
	this.instance_38.setTransform(76.9,207.6,1,1,0,0,0,16.8,5.6);

	this.timeline.addTween(cjs.Tween.get(this.instance_38).wait(18).to({y:219.1},6,cjs.Ease.get(-0.99)).to({y:230.6},12,cjs.Ease.get(1)).wait(5).to({y:231.1},6,cjs.Ease.get(0.5)).to({y:223.1},4,cjs.Ease.get(-0.49)).to({y:215.6},3,cjs.Ease.get(1)).to({_off:true},1).wait(202));

	// block_2_mc
	this.instance_39 = new lib.block_2_mc();
	this.instance_39.setTransform(0,129);

	this.timeline.addTween(cjs.Tween.get(this.instance_39).wait(18).to({y:146.5},6,cjs.Ease.get(-0.99)).to({y:164},12,cjs.Ease.get(1)).wait(5).to({scaleY:0.51,y:182},6,cjs.Ease.get(0.5)).to({y:174},4,cjs.Ease.get(-0.49)).to({y:166},4,cjs.Ease.get(1)).wait(1).to({y:181},6,cjs.Ease.get(-0.99)).to({y:196},12,cjs.Ease.get(1)).wait(5).to({scaleX:0.33,scaleY:0.43,y:236},6,cjs.Ease.get(0.5)).to({y:231},4,cjs.Ease.get(-0.49)).to({y:226},4,cjs.Ease.get(1)).wait(36).to({x:50},0).wait(25).to({scaleX:0.34,x:100,y:236},8,cjs.Ease.get(0.75)).to({y:231},4,cjs.Ease.get(-0.49)).to({y:226},4,cjs.Ease.get(1)).wait(87));

	// newMessage_mc
	this.instance_40 = new lib.newMessage_mc();

	this.timeline.addTween(cjs.Tween.get(this.instance_40).wait(18).to({y:-34.8},0).to({y:-17.3},6,cjs.Ease.get(-0.99)).to({y:0},12,cjs.Ease.get(1)).to({_off:true},5).wait(15).to({y:-34.8,_off:false},0).to({y:-17.3},6,cjs.Ease.get(-0.99)).to({y:0},12,cjs.Ease.get(1)).to({_off:true},5).wait(178));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,151,265);

})(lib = lib||{}, images = images||{}, createjs = createjs||{});
var lib, images, createjs;